from flask import Flask, request, render_template, send_file, session, redirect, url_for
import yt_dlp
import os
import time
import logging

app = Flask(__name__)
app.secret_key = 'your_secret_key_here'  # Replace with a secure key (e.g., secrets.token_hex(16))

# Set up simple logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('youtube_downloader')

# Translation dictionary
translations = {
  "ar": {
    "title": "تنزيل فيديوهات يوتيوب بسهولة",
    "description": "قم بتنزيل فيديوهات يوتيوب بصيغ MP4 وMP3 بسهولة وبدون إعلانات ومجانًا.",
    "brand": "YTGrab",
    "faq": "الأسئلة الشائعة",
    "language": "العربية",
    "subtitle": "قم بتنزيل الفيديوهات والصوتيات بصيغ متعددة بسهولة وسرعة",
    "placeholder": "الصق رابط يوتيوب هنا...",
    "download_button": "تنزيل",
    "choose_format": "اختر الصيغة",
    "back": "رجوع",
    "support": "ندعم تنزيل الفيديوهات من يوتيوب بجميع الصيغ والجودات المتاحة.",
    "format": "الصيغة",
    "size": "الحجم",
    "download": "تنزيل",
    "instant_download": "تنزيل فوري",
    "instant_download_desc": "احصل على فيديوهاتك في ثوانٍ مع خوادمنا عالية السرعة",
    "multiple_formats": "صيغ متعددة",
    "multiple_formats_desc": "MP4، MP3، 1080p، 4K، والعديد من الصيغ الأخرى المتاحة",
    "easy_to_use": "سهل الاستخدام",
    "easy_to_use_desc": "الصق الرابط وقم بالتنزيل - لا يتطلب تسجيل",
    "how_it_works": "كيف يعمل",
    "step1_title": "نسخ الرابط",
    "step1_desc": "انسخ رابط فيديو يوتيوب",
    "step2_title": "لصق الرابط",
    "step2_desc": "الصق في المربع أعلاه",
    "step3_title": "اختر الصيغة",
    "step3_desc": "حدد الجودة/الصيغة",
    "step4_title": "تنزيل",
    "step4_desc": "احصل على ملفك فورًا",
    "faq_title": "الأسئلة الشائعة",
    "faq1_q": "هل تنزيل فيديوهات يوتيوب مجاني؟",
    "faq1_a": "نعم، خدمتنا مجانية تمامًا. يمكنك تنزيل الفيديوهات بصيغ وجودات مختلفة بدون أي تكلفة.",
    "faq2_q": "ما هي صيغ الفيديو المدعومة؟",
    "faq2_a": "ندعم صيغًا متنوعة بما في ذلك MP4 وWebM للفيديو، وMP3 للصوت. يمكنك الاختيار من خيارات الجودة من 360p إلى 4K (عند توفرها).",
    "faq3_q": "هل تنزيل فيديوهات يوتيوب قانوني؟",
    "faq3_a": "تنزيل الفيديوهات للاستخدام الشخصي مقبول بشكل عام. ومع ذلك، يرجى احترام قوانين حقوق الطبع والنشر وحقوق صناع المحتوى. لا تقم بتوزيع المحتوى المُنزّل أو استخدامه لأغراض تجارية دون إذن مناسب.",
    "faq4_q": "كيف أقوم بتنزيل فيديو يوتيوب؟",
    "faq4_a": "1. انسخ رابط فيديو يوتيوب<br>2. الصقه في مربع الإدخال أعلاه<br>3. انتظر تحميل الصيغ المتاحة<br>4. اختر الصيغة والجودة المفضلة<br>5. انقر على زر التنزيل",
    "faq5_q": "هل هناك حدود للتنزيل؟",
    "faq5_a": "لا توجد حدود صارمة على التنزيلات. ومع ذلك، نوصي بالاستخدام المعقول لضمان بقاء الخدمة متاحة للجميع. الملفات الكبيرة جدًا قد تستغرق وقتًا أطول للمعالجة.",
    "copyright": "© 2025 YTGrab. جميع الحقوق محفوظة.",
    "privacy_policy": "سياسة الخصوصية",
    "terms": "الشروط",
    "contact": "اتصل بنا",
    "url_error": "يرجى إدخال رابط يوتيوب صالح"
  },
  "bn": {
    "title": "यूट्यूब वीडियो आसानी से डाउनलोड करें",
    "description": "यूट्यूब वीडियो MP4 और MP3 फॉर्मेट में आसानी से बिना विज्ञापन और मुफ्त में डाउनलोड करें।",
    "brand": "YTGrab",
    "faq": "अक्सर पूछे जाने वाले प्रश्न",
    "language": "भोजपुरी",
    "subtitle": "कई फॉर्मेट में वीडियो और ऑडियो जल्दी और आसानी से डाउनलोड करें",
    "placeholder": "यूट्यूब लिंक यहाँ पेस्ट करें...",
    "download_button": "डाउनलोड",
    "choose_format": "फॉर्मेट चुनें",
    "back": "वापस",
    "support": "हम यूट्यूब से सभी उपलब्ध फॉर्मेट और गुणवत्ता में वीडियो डाउनलोड करने का समर्थन करते हैं।",
    "format": "फॉर्मेट",
    "size": "आकार",
    "download": "डाउनलोड",
    "instant_download": "तुरंत डाउनलोड",
    "instant_download_desc": "हमारे हाई-स्पीड सर्वर के साथ सेकंडों में अपने वीडियो प्राप्त करें",
    "multiple_formats": "कई फॉर्मेट",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K, और कई अन्य फॉर्मेट उपलब्ध हैं",
    "easy_to_use": "उपयोग में आसान",
    "easy_to_use_desc": "लिंक पेस्ट करें और डाउनलोड करें - कोई पंजीकरण आवश्यक नहीं",
    "how_it_works": "यह कैसे काम करता है",
    "step1_title": "URL कॉपी करें",
    "step1_desc": "यूट्यूब वीडियो लिंक कॉपी करें",
    "step2_title": "लिंक पेस्ट करें",
    "step2_desc": "ऊपर दिए बॉक्स में पेस्ट करें",
    "step3_title": "फॉर्मेट चुनें",
    "step3_desc": "गुणवत्ता/फॉर्मेट चुनें",
    "step4_title": "डाउनलोड",
    "step4_desc": "अपनी फाइल तुरंत प्राप्त करें",
    "faq_title": "अक्सर पूछे जाने वाले प्रश्न",
    "faq1_q": "क्या यूट्यूब वीडियो डाउनलोड करना मुफ्त है?",
    "faq1_a": "हाँ, हमारी सेवा पूरी तरह से मुफ्त है। आप विभिन्न फॉर्मेट और गुणवत्ता में वीडियो बिना किसी लागत के डाउनलोड कर सकते हैं।",
    "faq2_q": "कौन से वीडियो फॉर्मेट समर्थित हैं?",
    "faq2_a": "हम विभिन्न फॉर्मेट का समर्थन करते हैं, जिसमें वीडियो के लिए MP4, WebM और ऑडियो के लिए MP3 शामिल हैं। आप 360p से 4K तक विभिन्न गुणवत्ता विकल्पों में से चुन सकते हैं (जब उपलब्ध हो)।",
    "faq3_q": "क्या यूट्यूब वीडियो डाउनलोड करना कानूनी है?",
    "faq3_a": "निजी उपयोग के लिए वीडियो डाउनलोड करना सामान्य रूप से स्वीकार्य है। हालांकि, कृपया कॉपीराइट कानूनों और सामग्री निर्माताओं के अधिकारों का सम्मान करें। बिना उचित प्राधिकरण के डाउनलोड किए गए सामग्री को वितरित या व्यावसायिक उद्देश्यों के लिए उपयोग न करें।",
    "faq4_q": "मैं यूट्यूब वीडियो कैसे डाउनलोड करूँ?",
    "faq4_a": "1. यूट्यूब वीडियो URL कॉपी करें<br>2. इसे ऊपर दिए इनपुट बॉक्स में पेस्ट करें<br>3. उपलब्ध फॉर्मेट लोड होने की प्रतीक्षा करें<br>4. अपने पसंदीदा फॉर्मेट और गुणवत्ता चुनें<br>5. डाउनलोड बटन पर क्लिक करें",
    "faq5_q": "क्या डाउनलोड की कोई सीमा है?",
    "faq5_a": "डाउनलोड पर कोई सख्त सीमा नहीं है। हालांकि, हम उचित उपयोग की सलाह देते हैं ताकि सेवा सभी के लिए उपलब्ध रहे। बहुत बड़े फाइलें प्रोसेस करने में अधिक समय ले सकती हैं।",
    "copyright": "© 2025 YTGrab। सर्वाधिकार सुरक्षित।",
    "privacy_policy": "गोपनीयता नीति",
    "terms": "शर्तें",
    "contact": "संपर्क करें",
    "url_error": "कृपया एक मान्य यूट्यूब URL दर्ज करें"
  },
  "cs": {
    "title": "Stahujte videa z YouTube snadno",
    "description": "Stahujte videa z YouTube ve formátech MP4 a MP3 snadno, bez reklam a zdarma.",
    "brand": "YTGrab",
    "faq": "Často kladené otázky",
    "language": "Čeština",
    "subtitle": "Stahujte videa a zvuk v různých formátech rychle a jednoduše",
    "placeholder": "Sem vložte odkaz na YouTube...",
    "download_button": "Stáhnout",
    "choose_format": "Vyberte formát",
    "back": "Zpět",
    "support": "Podporujeme stahování videí z YouTube ve všech dostupných formátech a kvalitách.",
    "format": "Formát",
    "size": "Velikost",
    "download": "Stáhnout",
    "instant_download": "Okamžité stažení",
    "instant_download_desc": "Získejte svá videa během sekund s našimi vysokorychlostními servery",
    "multiple_formats": "Více formátů",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K a mnoho dalších dostupných formátů",
    "easy_to_use": "Snadné použití",
    "easy_to_use_desc": "Vložte odkaz a stáhněte – není vyžadována registrace",
    "how_it_works": "Jak to funguje",
    "step1_title": "Kopírovat URL",
    "step1_desc": "Zkopírujte odkaz na video z YouTube",
    "step2_title": "Vložit odkaz",
    "step2_desc": "Vložte do pole výše",
    "step3_title": "Vybrat formát",
    "step3_desc": "Vyberte kvalitu/formát",
    "step4_title": "Stáhnout",
    "step4_desc": "Získejte svůj soubor okamžitě",
    "faq_title": "Často kladené otázky",
    "faq1_q": "Je stahování videí z YouTube zdarma?",
    "faq1_a": "Ano, naše služba je zcela zdarma. Můžete stahovat videa v různých formátech a kvalitách bez jakýchkoliv nákladů.",
    "faq2_q": "Jaké formáty videí jsou podporovány?",
    "faq2_a": "Podporujeme různé formáty včetně MP4, WebM pro video a MP3 pro zvuk. Můžete si vybrat z různých možností kvality od 360p až po 4K (pokud je k dispozici).",
    "faq3_q": "Je stahování videí z YouTube legální?",
    "faq3_a": "Stahování videí pro osobní použití je obecně přijatelné. Respektujte však autorská práva a práva tvůrců obsahu. Nestahujte ani nepoužívejte stažený obsah pro komerční účely bez řádného povolení.",
    "faq4_q": "Jak stáhnout video z YouTube?",
    "faq4_a": "1. Zkopírujte URL videa z YouTube<br>2. Vložte ji do vstupního pole výše<br>3. Počkejte, až se načtou dostupné formáty<br>4. Vyberte preferovaný formát a kvalitu<br>5. Klikněte na tlačítko stáhnout",
    "faq5_q": "Jsou nějaká omezení stahování?",
    "faq5_a": "Na stahování nejsou žádná přísná omezení. Doporučujeme však rozumné používání, aby služba zůstala dostupná pro všechny. Velmi velké soubory mohou vyžadovat delší čas na zpracování.",
    "copyright": "© 2025 YTGrab. Všechna práva vyhrazena.",
    "privacy_policy": "Zásady ochrany osobních údajů",
    "terms": "Podmínky",
    "contact": "Kontakt",
    "url_error": "Zadejte prosím platnou adresu URL YouTube"
  },
  "de": {
    "title": "YouTube-Videos einfach herunterladen",
    "description": "Laden Sie YouTube-Videos in MP4- und MP3-Formaten einfach, ohne Werbung und kostenlos herunter.",
    "brand": "YTGrab",
    "faq": "Häufig gestellte Fragen",
    "language": "Deutsch",
    "subtitle": "Laden Sie Videos und Audio in mehreren Formaten schnell und einfach herunter",
    "placeholder": "YouTube-Link hier einfügen...",
    "download_button": "Herunterladen",
    "choose_format": "Format wählen",
    "back": "Zurück",
    "support": "Wir unterstützen das Herunterladen von Videos von YouTube in allen verfügbaren Formaten und Qualitäten.",
    "format": "Format",
    "size": "Größe",
    "download": "Herunterladen",
    "instant_download": "Sofortiger Download",
    "instant_download_desc": "Holen Sie sich Ihre Videos in Sekunden mit unseren Hochgeschwindigkeitsservern",
    "multiple_formats": "Mehrere Formate",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K und viele weitere Formate verfügbar",
    "easy_to_use": "Einfach zu bedienen",
    "easy_to_use_desc": "Link einfügen und herunterladen – keine Registrierung erforderlich",
    "how_it_works": "So funktioniert es",
    "step1_title": "URL kopieren",
    "step1_desc": "YouTube-Video-Link kopieren",
    "step2_title": "Link einfügen",
    "step2_desc": "In das Feld oben einfügen",
    "step3_title": "Format wählen",
    "step3_desc": "Qualität/Format auswählen",
    "step4_title": "Herunterladen",
    "step4_desc": "Ihre Datei sofort erhalten",
    "faq_title": "Häufig gestellte Fragen",
    "faq1_q": "Ist das Herunterladen von YouTube-Videos kostenlos?",
    "faq1_a": "Ja, unser Dienst ist völlig kostenlos. Sie können Videos in verschiedenen Formaten und Qualitäten ohne Kosten herunterladen.",
    "faq2_q": "Welche Videoformate werden unterstützt?",
    "faq2_a": "Wir unterstützen verschiedene Formate, einschließlich MP4, WebM für Videos und MP3 für Audio. Sie können aus verschiedenen Qualitätsoptionen von 360p bis 4K wählen (sofern verfügbar).",
    "faq3_q": "Ist das Herunterladen von YouTube-Videos legal?",
    "faq3_a": "Das Herunterladen von Videos für den persönlichen Gebrauch ist im Allgemeinen akzeptabel. Bitte respektieren Sie jedoch Urheberrechtsgesetze und die Rechte der Inhaltsersteller. Verteilen oder nutzen Sie heruntergeladene Inhalte nicht ohne entsprechende Genehmigung für kommerzielle Zwecke.",
    "faq4_q": "Wie lade ich ein YouTube-Video herunter?",
    "faq4_a": "1. Kopieren Sie die URL des YouTube-Videos<br>2. Fügen Sie sie in das Eingabefeld oben ein<br>3. Warten Sie, bis die verfügbaren Formate geladen sind<br>4. Wählen Sie Ihr bevorzugtes Format und Ihre Qualität<br>5. Klicken Sie auf die Schaltfläche zum Herunterladen",
    "faq5_q": "Gibt es Download-Limits?",
    "faq5_a": "Es gibt keine strikten Download-Limits. Wir empfehlen jedoch einen angemessenen Gebrauch, um sicherzustellen, dass der Dienst für alle verfügbar bleibt. Sehr große Dateien können länger zur Verarbeitung benötigen.",
    "copyright": "© 2025 YTGrab. Alle Rechte vorbehalten.",
    "privacy_policy": "Datenschutzrichtlinie",
    "terms": "Nutzungsbedingungen",
    "contact": "Kontakt",
    "url_error": "Bitte geben Sie eine gültige YouTube-URL ein"
  },
  "el": {
    "title": "Κατεβάστε βίντεο YouTube εύκολα",
    "description": "Κατεβάστε βίντεο YouTube σε μορφές MP4 και MP3 εύκολα, χωρίς διαφημίσεις και δωρεάν.",
    "brand": "YTGrab",
    "faq": "Συχνές Ερωτήσεις",
    "language": "Ελληνικά",
    "subtitle": "Κατεβάστε βίντεο και ήχο σε πολλαπλές μορφές γρήγορα και εύκολα",
    "placeholder": "Επικολλήστε το σύνδεσμο YouTube εδώ...",
    "download_button": "Λήψη",
    "choose_format": "Επιλέξτε Μορφή",
    "back": "Πίσω",
    "support": "Υποστηρίζουμε τη λήψη βίντεο από το YouTube σε όλες τις διαθέσιμες μορφές και ποιότητες.",
    "format": "Μορφή",
    "size": "Μέγεθος",
    "download": "Λήψη",
    "instant_download": "Άμεση Λήψη",
    "instant_download_desc": "Αποκτήστε τα βίντεό σας σε δευτερόλεπτα με τους γρήγορους διακομιστές μας",
    "multiple_formats": "Πολλαπλές Μορφές",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K, και πολλές άλλες μορφές διαθέσιμες",
    "easy_to_use": "Εύκολο στη Χρήση",
    "easy_to_use_desc": "Επικολλήστε τον σύνδεσμο και κατεβάστε - δεν απαιτείται εγγραφή",
    "how_it_works": "Πώς Λειτουργεί",
    "step1_title": "Αντιγραφή URL",
    "step1_desc": "Αντιγράψτε τον σύνδεσμο βίντεο YouTube",
    "step2_title": "Επικόλληση Συνδέσμου",
    "step2_desc": "Επικολλήστε στο πλαίσιο παραπάνω",
    "step3_title": "Επιλογή Μορφής",
    "step3_desc": "Επιλέξτε ποιότητα/μορφή",
    "step4_title": "Λήψη",
    "step4_desc": "Αποκτήστε το αρχείο σας αμέσως",
    "faq_title": "Συχνές Ερωτήσεις",
    "faq1_q": "Είναι δωρεάν η λήψη βίντεο από το YouTube;",
    "faq1_a": "Ναι, η υπηρεσία μας είναι εντελώς δωρεάν. Μπορείτε να κατεβάσετε βίντεο σε διάφορες μορφές και ποιότητες χωρίς κανένα κόστος.",
    "faq2_q": "Ποιες μορφές βίντεο υποστηρίζονται;",
    "faq2_a": "Υποστηρίζουμε διάφορες μορφές, συμπεριλαμβανομένων των MP4, WebM για βίντεο και MP3 για ήχο. Μπορείτε να επιλέξετε από διαφορετικές επιλογές ποιότητας, από 360p έως 4K (όταν είναι διαθέσιμες).",
    "faq3_q": "Είναι νόμιμο να κατεβάζω βίντεο από το YouTube;",
    "faq3_a": "Η λήψη βίντεο για προσωπική χρήση είναι γενικά αποδεκτή. Ωστόσο, παρακαλούμε σεβαστείτε τους νόμους περί πνευματικής ιδιοκτησίας και τα δικαιώματα των δημιουργών περιεχομένου. Μην διανέμετε ή χρησιμοποιείτε το κατεβασμένο περιεχόμενο για εμπορικούς σκοπούς χωρίς κατάλληλη άδεια.",
    "faq4_q": "Πώς κατεβάζω ένα βίντεο από το YouTube;",
    "faq4_a": "1. Αντιγράψτε το URL του βίντεο YouTube<br>2. Επικολλήστε το στο πλαίσιο εισαγωγής παραπάνω<br>3. Περιμένετε να φορτώσουν οι διαθέσιμες μορφές<br>4. Επιλέξτε την προτιμώμενη μορφή και ποιότητα<br>5. Κάντε κλικ στο κουμπί λήψης",
    "faq5_q": "Υπάρχουν όρια λήψης;",
    "faq5_a": "Δεν υπάρχουν αυστηρά όρια λήψης. Ωστόσο, συνιστούμε λογική χρήση για να διασφαλιστεί ότι η υπηρεσία παραμένει διαθέσιμη για όλους. Πολύ μεγάλα αρχεία μπορεί να χρειάζονται περισσότερο χρόνο για επεξεργασία.",
    "copyright": "© 2025 YTGrab. Με επιφύλαξη παντός δικαιώματος.",
    "privacy_policy": "Πολιτική Απορρήτου",
    "terms": "Όροι",
    "contact": "Επικοινωνία",
    "url_error": "Παρακαλώ εισαγάγετε έγκυρο URL του YouTube"
  },
  "en": {
    "title": "Download YouTube Videos Easily",
    "description": "Download YouTube videos in MP4 and MP3 formats easily without ads and for free.",
    "brand": "YTGrab",
    "faq": "FAQ",
    "language": "English",
    "subtitle": "Download videos and audio in multiple formats quickly and easily",
    "placeholder": "Paste YouTube link here...",
    "download_button": "Download",
    "choose_format": "Choose Format",
    "back": "Back",
    "support": "We support downloading videos from YouTube in all available formats and qualities.",
    "format": "Format",
    "size": "Size",
    "download": "Download",
    "instant_download": "Instant Download",
    "instant_download_desc": "Get your videos in seconds with our high-speed servers",
    "multiple_formats": "Multiple Formats",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K, and many more formats available",
    "easy_to_use": "Easy to Use",
    "easy_to_use_desc": "Paste link and download - no registration required",
    "how_it_works": "How It Works",
    "step1_title": "Copy URL",
    "step1_desc": "Copy YouTube video link",
    "step2_title": "Paste Link",
    "step2_desc": "Paste in the box above",
    "step3_title": "Choose Format",
    "step3_desc": "Select quality/format",
    "step4_title": "Download",
    "step4_desc": "Get your file instantly",
    "faq_title": "Frequently Asked Questions",
    "faq1_q": "Is it free to download YouTube videos?",
    "faq1_a": "Yes, our service is completely free to use. You can download videos in various formats and qualities without any cost.",
    "faq2_q": "What video formats are supported?",
    "faq2_a": "We support various formats including MP4, WebM for video, and MP3 for audio. You can choose from different quality options ranging from 360p to 4K (when available).",
    "faq3_q": "Is it legal to download YouTube videos?",
    "faq3_a": "Downloading videos for personal use is generally acceptable. However, please respect copyright laws and content creators' rights. Do not distribute or use downloaded content for commercial purposes without proper authorization.",
    "faq4_q": "How do I download a YouTube video?",
    "faq4_a": "1. Copy the YouTube video URL<br>2. Paste it in the input box above<br>3. Wait for the available formats to load<br>4. Choose your preferred format and quality<br>5. Click the download button",
    "faq5_q": "Are there any download limits?",
    "faq5_a": "There are no strict limits on downloads. However, we recommend reasonable usage to ensure the service remains available for everyone. Very large files may take longer to process.",
    "copyright": "© 2025 YTGrab. All rights reserved.",
    "privacy_policy": "Privacy Policy",
    "terms": "Terms",
    "contact": "Contact",
    "url_error": "Please enter a valid YouTube URL"
  },
  "es": {
    "title": "Descarga Videos de YouTube Fácilmente",
    "description": "Descarga videos de YouTube en formatos MP4 y MP3 fácilmente, sin anuncios y gratis.",
    "brand": "YTGrab",
    "faq": "Preguntas Frecuentes",
    "language": "Español",
    "subtitle": "Descarga videos y audio en múltiples formatos de forma rápida y sencilla",
    "placeholder": "Pega el enlace de YouTube aquí...",
    "download_button": "Descargar",
    "choose_format": "Elegir Formato",
    "back": "Volver",
    "support": "Soportamos la descarga de videos de YouTube en todos los formatos y calidades disponibles.",
    "format": "Formato",
    "size": "Tamaño",
    "download": "Descargar",
    "instant_download": "Descarga Instantánea",
    "instant_download_desc": "Obtén tus videos en segundos con nuestros servidores de alta velocidad",
    "multiple_formats": "Múltiples Formatos",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K, y muchos más formatos disponibles",
    "easy_to_use": "Fácil de Usar",
    "easy_to_use_desc": "Pega el enlace y descarga - no requiere registro",
    "how_it_works": "Cómo Funciona",
    "step1_title": "Copiar URL",
    "step1_desc": "Copia el enlace del video de YouTube",
    "step2_title": "Pegar Enlace",
    "step2_desc": "Pega en el cuadro de arriba",
    "step3_title": "Elegir Formato",
    "step3_desc": "Selecciona calidad/formato",
    "step4_title": "Descargar",
    "step4_desc": "Obtén tu archivo al instante",
    "faq_title": "Preguntas Frecuentes",
    "faq1_q": "¿Es gratis descargar videos de YouTube?",
    "faq1_a": "Sí, nuestro servicio es completamente gratuito. Puedes descargar videos en varios formatos y calidades sin costo alguno.",
    "faq2_q": "¿Qué formatos de video son compatibles?",
    "faq2_a": "Soportamos varios formatos, incluyendo MP4, WebM para video, y MP3 para audio. Puedes elegir entre diferentes opciones de calidad, desde 360p hasta 4K (cuando esté disponible).",
    "faq3_q": "¿Es legal descargar videos de YouTube?",
    "faq3_a": "Descargar videos para uso personal es generalmente aceptable. Sin embargo, respeta las leyes de derechos de autor y los derechos de los creadores de contenido. No distribuyas ni uses el contenido descargado con fines comerciales sin autorización adecuada.",
    "faq4_q": "¿Cómo descargo un video de YouTube?",
    "faq4_a": "1. Copia la URL del video de YouTube<br>2. Pégala en el cuadro de entrada de arriba<br>3. Espera a que se carguen los formatos disponibles<br>4. Elige tu formato y calidad preferidos<br>5. Haz clic en el botón de descarga",
    "faq5_q": "¿Hay límites de descarga?",
    "faq5_a": "No hay límites estrictos en las descargas. Sin embargo, recomendamos un uso razonable para garantizar que el servicio permanezca disponible para todos. Los archivos muy grandes pueden tardar más en procesarse.",
    "copyright": "© 2025 YTGrab. Todos los derechos reservados.",
    "privacy_policy": "Política de Privacidad",
    "terms": "Términos",
    "contact": "Contacto",
    "url_error": "Por favor, introduce una URL de YouTube válida"
  },
  "fa": {
    "title": "دانلود آسان ویدیوهای یوتیوب",
    "description": "ویدیوهای یوتیوب را در فرمت‌های MP4 و MP3 به راحتی، بدون تبلیغات و رایگان دانلود کنید.",
    "brand": "YTGrab",
    "faq": "سوالات متداول",
    "language": "فارسی",
    "subtitle": "ویدیوها و صوت‌ها را در فرمت‌های مختلف به سرعت و به آسانی دانلود کنید",
    "placeholder": "لینک یوتیوب را اینجا جای‌گذاری کنید...",
    "download_button": "دانلود",
    "choose_format": "انتخاب فرمت",
    "back": "بازگشت",
    "support": "ما از دانلود ویدیوهای یوتیوب در تمام فرمت‌ها و کیفیت‌های موجود پشتیبانی می‌کنیم.",
    "format": "فرمت",
    "size": "اندازه",
    "download": "دانلود",
    "instant_download": "دانلود فوری",
    "instant_download_desc": "ویدیوهای خود را در چند ثانیه با سرورهای پرسرعت ما دریافت کنید",
    "multiple_formats": "فرمت‌های متعدد",
    "multiple_formats_desc": "MP4، MP3، 1080p، 4K و بسیاری از فرمت‌های دیگر در دسترس هستند",
    "easy_to_use": "آسان برای استفاده",
    "easy_to_use_desc": "لینک را جای‌گذاری کنید و دانلود کنید - بدون نیاز به ثبت‌نام",
    "how_it_works": "چگونه کار می‌کند",
    "step1_title": "کپی URL",
    "step1_desc": "لینک ویدیوی یوتیوب را کپی کنید",
    "step2_title": "جای‌گذاری لینک",
    "step2_desc": "در کادر بالا جای‌گذاری کنید",
    "step3_title": "انتخاب فرمت",
    "step3_desc": "کیفیت/فرمت را انتخاب کنید",
    "step4_title": "دانلود",
    "step4_desc": "فایل خود را فوراً دریافت کنید",
    "faq_title": "سوالات متداول",
    "faq1_q": "آیا دانلود ویدیوهای یوتیوب رایگان است؟",
    "faq1_a": "بله، سرویس ما کاملاً رایگان است. شما می‌توانید ویدیوها را در فرمت‌ها و کیفیت‌های مختلف بدون هیچ هزینه‌ای دانلود کنید.",
    "faq2_q": "چه فرمت‌های ویدیویی پشتیبانی می‌شوند؟",
    "faq2_a": "ما از فرمت‌های مختلفی از جمله MP4، WebM برای ویدیو و MP3 برای صوت پشتیبانی می‌کنیم. می‌توانید از گزینه‌های کیفیت مختلف از 360p تا 4K انتخاب کنید (در صورت موجود بودن).",
    "faq3_q": "آیا دانلود ویدیوهای یوتیوب قانونی است؟",
    "faq3_a": "دانلود ویدیوها برای استفاده شخصی معمولاً قابل قبول است. با این حال، لطفاً قوانین کپی‌رایت و حقوق خالقان محتوا را رعایت کنید. محتوای دانلود شده را بدون مجوز مناسب برای مقاصد تجاری توزیع یا استفاده نکنید.",
    "faq4_q": "چگونه یک ویدیوی یوتیوب را دانلود کنم؟",
    "faq4_a": "1. URL ویدیوی یوتیوب را کپی کنید<br>2. آن را در کادر ورودی بالا جای‌گذاری کنید<br>3. منتظر بارگذاری فرمت‌های موجود بمانید<br>4. فرمت و کیفیت مورد نظر خود را انتخاب کنید<br>5. روی دکمه دانلود کلیک کنید",
    "faq5_q": "آیا محدودیت دانلودی وجود دارد؟",
    "faq5_a": "هیچ محدودیت سختی برای دانلود وجود ندارد. با این حال، ما استفاده معقول را توصیه می‌کنیم تا سرویس برای همه در دسترس باقی بماند. فایل‌های بسیار بزرگ ممکن است زمان بیشتری برای پردازش نیاز داشته باشند.",
    "copyright": "© 2025 YTGrab. تمامی حقوق محفوظ است.",
    "privacy_policy": "سیاست حفظ حریم خصوصی",
    "terms": "شرایط",
    "contact": "تماس",
    "url_error": "لطفاً یک URL معتبر یوتیوب وارد کنید"
  },
  "fr": {
    "title": "Téléchargez des vidéos YouTube facilement",
    "description": "Téléchargez des vidéos YouTube aux formats MP4 et MP3 facilement, sans publicités et gratuitement.",
    "brand": "YTGrab",
    "faq": "Questions Fréquentes",
    "language": "Français",
    "subtitle": "Téléchargez des vidéos et de l’audio dans plusieurs formats rapidement et facilement",
    "placeholder": "Collez le lien YouTube ici...",
    "download_button": "Télécharger",
    "choose_format": "Choisir le format",
    "back": "Retour",
    "support": "Nous prenons en charge le téléchargement de vidéos YouTube dans tous les formats et qualités disponibles.",
    "format": "Format",
    "size": "Taille",
    "download": "Télécharger",
    "instant_download": "Téléchargement instantané",
    "instant_download_desc": "Obtenez vos vidéos en quelques secondes avec nos serveurs à haute vitesse",
    "multiple_formats": "Formats multiples",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K, et bien d’autres formats disponibles",
    "easy_to_use": "Facile à utiliser",
    "easy_to_use_desc": "Collez le lien et téléchargez - aucune inscription requise",
    "how_it_works": "Comment ça marche",
    "step1_title": "Copier l’URL",
    "step1_desc": "Copiez le lien de la vidéo YouTube",
    "step2_title": "Coller le lien",
    "step2_desc": "Collez dans la boîte ci-dessus",
    "step3_title": "Choisir le format",
    "step3_desc": "Sélectionnez la qualité/format",
    "step4_title": "Télécharger",
    "step4_desc": "Obtenez votre fichier instantanément",
    "faq_title": "Questions Fréquentes",
    "faq1_q": "Est-il gratuit de télécharger des vidéos YouTube ?",
    "faq1_a": "Oui, notre service est entièrement gratuit. Vous pouvez télécharger des vidéos dans différents formats et qualités sans aucun coût.",
    "faq2_q": "Quels formats de vidéo sont pris en charge ?",
    "faq2_a": "Nous prenons en charge divers formats, y compris MP4, WebM pour la vidéo et MP3 pour l’audio. Vous pouvez choisir parmi différentes options de qualité allant de 360p à 4K (lorsque disponible).",
    "faq3_q": "Est-il légal de télécharger des vidéos YouTube ?",
    "faq3_a": "Télécharger des vidéos pour un usage personnel est généralement acceptable. Cependant, veuillez respecter les lois sur le droit d’auteur et les droits des créateurs de contenu. Ne distribuez pas ou n’utilisez pas le contenu téléchargé à des fins commerciales sans autorisation appropriée.",
    "faq4_q": "Comment télécharger une vidéo YouTube ?",
    "faq4_a": "1. Copiez l’URL de la vidéo YouTube<br>2. Collez-la dans la boîte de saisie ci-dessus<br>3. Attendez que les formats disponibles se chargent<br>4. Choisissez votre format et qualité préférés<br>5. Cliquez sur le bouton de téléchargement",
    "faq5_q": "Y a-t-il des limites de téléchargement ?",
    "faq5_a": "Il n’y a pas de limites strictes sur les téléchargements. Cependant, nous recommandons une utilisation raisonnable pour garantir que le service reste disponible pour tous. Les fichiers très volumineux peuvent prendre plus de temps à traiter.",
    "copyright": "© 2025 YTGrab. Tous droits réservés.",
    "privacy_policy": "Politique de confidentialité",
    "terms": "Conditions",
    "contact": "Contact",
    "url_error": "Veuillez entrer une URL YouTube valide"
  },
  "hi": {
    "title": "यूट्यूब वीडियो आसानी से डाउनलोड करें",
    "description": "यूट्यूब वीडियो को MP4 और MP3 प्रारूपों में आसानी से, बिना विज्ञापनों के और मुफ्त में डाउनलोड करें।",
    "brand": "YTGrab",
    "faq": "अक्सर पूछे जाने वाले प्रश्न",
    "language": "हिन्दी",
    "subtitle": "कई प्रारूपों में वीडियो और ऑडियो जल्दी और आसानी से डाउनलोड करें",
    "placeholder": "यहाँ यूट्यूब लिंक पेस्ट करें...",
    "download_button": "डाउनलोड",
    "choose_format": "प्रारूप चुनें",
    "back": "वापस",
    "support": "हम यूट्यूब से सभी उपलब्ध प्रारूपों और गुणवत्ता में वीडियो डाउनलोड करने का समर्थन करते हैं।",
    "format": "प्रारूप",
    "size": "आकार",
    "download": "डाउनलोड",
    "instant_download": "तत्काल डाउनलोड",
    "instant_download_desc": "हमारे उच्च गति सर्वरों के साथ सेकंडों में अपने वीडियो प्राप्त करें",
    "multiple_formats": "कई प्रारूप",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K, और कई अन्य प्रारूप उपलब्ध हैं",
    "easy_to_use": "उपयोग में आसान",
    "easy_to_use_desc": "लिंक पेस्ट करें और डाउनलोड करें - कोई पंजीकरण आवश्यक नहीं",
    "how_it_works": "यह कैसे काम करता है",
    "step1_title": "URL कॉपी करें",
    "step1_desc": "यूट्यूब वीडियो लिंक कॉपी करें",
    "step2_title": "लिंक पेस्ट करें",
    "step2_desc": "ऊपर दिए बॉक्स में पेस्ट करें",
    "step3_title": "प्रारूप चुनें",
    "step3_desc": "गुणवत्ता/प्रारूप चुनें",
    "step4_title": "डाउनलोड",
    "step4_desc": "अपनी फाइल तुरंत प्राप्त करें",
    "faq_title": "अक्सर पूछे जाने वाले प्रश्न",
    "faq1_q": "क्या यूट्यूब वीडियो डाउनलोड करना मुफ्त है?",
    "faq1_a": "हाँ, हमारी सेवा पूरी तरह से मुफ्त है। आप विभिन्न प्रारूपों और गुणवत्ता में वीडियो बिना किसी लागत के डाउनलोड कर सकते हैं।",
    "faq2_q": "कौन से वीडियो प्रारूप समर्थित हैं?",
    "faq2_a": "हम विभिन्न प्रारूपों का समर्थन करते हैं, जिसमें वीडियो के लिए MP4, WebM और ऑडियो के लिए MP3 शामिल हैं। आप 360p से 4K तक विभिन्न गुणवत्ता विकल्पों में से चुन सकते हैं (जब उपलब्ध हो)।",
    "faq3_q": "क्या यूट्यूब वीडियो डाउनलोड करना कानूनी है?",
    "faq3_a": "निजी उपयोग के लिए वीडियो डाउनलोड करना सामान्य रूप से स्वीकार्य है। हालांकि, कृपया कॉपीराइट कानूनों और सामग्री निर्माताओं के अधिकारों का सम्मान करें। बिना उचित प्राधिकरण के डाउनलोड किए गए सामग्री को वितरित या व्यावसायिक उद्देश्यों के लिए उपयोग न करें।",
    "faq4_q": "मैं यूट्यूब वीडियो कैसे डाउनलोड करूँ?",
    "faq4_a": "1. यूट्यूब वीडियो URL कॉपी करें<br>2. इसे ऊपर दिए इनपुट बॉक्स में पेस्ट करें<br>3. उपलब्ध प्रारूपों के लोड होने की प्रतीक्षा करें<br>4. अपने पसंदीदा प्रारूप और गुणवत्ता चुनें<br>5. डाउनलोड बटन पर क्लिक करें",
    "faq5_q": "क्या डाउनलोड की कोई सीमा है?",
    "faq5_a": "डाउनलोड पर कोई सख्त सीमा नहीं है। हालांकि, हम उचित उपयोग की सलाह देते हैं ताकि सेवा सभी के लिए उपलब्ध रहे। बहुत बड़े फाइलें प्रोसेस करने में अधिक समय ले सकती हैं।",
    "copyright": "© 2025 YTGrab। सर्वाधिकार सुरक्षित।",
    "privacy_policy": "गोपनीयता नीति",
    "terms": "शर्तें",
    "contact": "संपर्क",
    "url_error": "कृपया एक मान्य यूट्यूब URL दर्ज करें"
  },
  "hu": {
    "title": "YouTube videók egyszerű letöltése",
    "description": "Töltsön le YouTube videókat MP4 és MP3 formátumban egyszerűen, reklámok nélkül és ingyen.",
    "brand": "YTGrab",
    "faq": "Gyakran Ismételt Kérdések",
    "language": "Magyar",
    "subtitle": "Töltsön le videókat és hangokat több formátumban gyorsan és egyszerűen",
    "placeholder": "Illessze be ide a YouTube linket...",
    "download_button": "Letöltés",
    "choose_format": "Formátum kiválasztása",
    "back": "Vissza",
    "support": "Támogatjuk a YouTube videók letöltését minden elérhető formátumban és minőségben.",
    "format": "Formátum",
    "size": "Méret",
    "download": "Letöltés",
    "instant_download": "Azonnali letöltés",
    "instant_download_desc": "Szerezze meg videóit másodpercek alatt nagy sebességű szervereinkkel",
    "multiple_formats": "Több formátum",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K és sok más formátum elérhető",
    "easy_to_use": "Könnyű használni",
    "easy_to_use_desc": "Illessze be a linket és töltsön le – nincs szükség regisztrációra",
    "how_it_works": "Hogyan működik",
    "step1_title": "URL másolása",
    "step1_desc": "Másolja a YouTube videó linkjét",
    "step2_title": "Link beillesztése",
    "step2_desc": "Illessze be a fenti mezőbe",
    "step3_title": "Formátum kiválasztása",
    "step3_desc": "Válassza ki a minőséget/formátumot",
    "step4_title": "Letöltés",
    "step4_desc": "Szerezze meg a fájlt azonnal",
    "faq_title": "Gyakran Ismételt Kérdések",
    "faq1_q": "Ingyenes a YouTube videók letöltése?",
    "faq1_a": "Igen, szolgáltatásunk teljesen ingyenes. Különböző formátumokban és minőségben tölthet le videókat minden költség nélkül.",
    "faq2_q": "Milyen videóformátumokat támogatunk?",
    "faq2_a": "Különböző formátumokat támogatunk, beleértve az MP4, WebM videókat és az MP3 hangokat. Különböző minőségi opciók közül választhat, 360p-től 4K-ig (ha elérhető).",
    "faq3_q": "Legális a YouTube videók letöltése?",
    "faq3_a": "Személyes használatra történő videóletöltés általában elfogadható. Kérjük azonban, tartsa tiszteletben a szerzői jogi törvényeket és a tartalomkészítők jogait. Ne terjessze vagy használja a letöltött tartalmat kereskedelmi célokra megfelelő engedély nélkül.",
    "faq4_q": "Hogyan tölthetek le egy YouTube videót?",
    "faq4_a": "1. Másolja a YouTube videó URL-jét<br>2. Illessze be a fenti beviteli mezőbe<br>3. Várja meg, amíg az elérhető formátumok betöltődnek<br>4. Válassza ki a kívánt formátumot és minőséget<br>5. Kattintson a letöltés gombra",
    "faq5_q": "Vannak letöltési korlátok?",
    "faq5_a": "Nincsenek szigorú letöltési korlátok. Azonban ésszerű használatot javaslunk annak érdekében, hogy a szolgáltatás mindenki számára elérhető maradjon. Nagyon nagy fájlok feldolgozása hosszabb időt vehet igénybe.",
    "copyright": "© 2025 YTGrab. Minden jog fenntartva.",
    "privacy_policy": "Adatvédelmi irányelvek",
    "terms": "Feltételek",
    "contact": "Kapcsolat",
    "url_error": "Kérjük, adjon meg egy érvényes YouTube URL-t"
  },
  "id": {
    "title": "Unduh Video YouTube dengan Mudah",
    "description": "Unduh video YouTube dalam format MP4 dan MP3 dengan mudah, tanpa iklan dan gratis.",
    "brand": "YTGrab",
    "faq": "Pertanyaan yang Sering Diajukan",
    "language": "Bahasa Indonesia",
    "subtitle": "Unduh video dan audio dalam berbagai format dengan cepat dan mudah",
    "placeholder": "Tempelkan tautan YouTube di sini...",
    "download_button": "Unduh",
    "choose_format": "Pilih Format",
    "back": "Kembali",
    "support": "Kami mendukung pengunduhan video dari YouTube dalam semua format dan kualitas yang tersedia.",
    "format": "Format",
    "size": "Ukuran",
    "download": "Unduh",
    "instant_download": "Unduh Instan",
    "instant_download_desc": "Dapatkan video Anda dalam hitungan detik dengan server berkecepatan tinggi kami",
    "multiple_formats": "Berbagai Format",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K, dan banyak lagi format yang tersedia",
    "easy_to_use": "Mudah Digunakan",
    "easy_to_use_desc": "Tempelkan tautan dan unduh - tidak perlu registrasi",
    "how_it_works": "Cara Kerja",
    "step1_title": "Salin URL",
    "step1_desc": "Salin tautan video YouTube",
    "step2_title": "Tempelkan Tautan",
    "step2_desc": "Tempelkan di kotak di atas",
    "step3_title": "Pilih Format",
    "step3_desc": "Pilih kualitas/format",
    "step4_title": "Unduh",
    "step4_desc": "Dapatkan file Anda seketika",
    "faq_title": "Pertanyaan yang Sering Diajukan",
    "faq1_q": "Apakah mengunduh video YouTube gratis?",
    "faq1_a": "Ya, layanan kami sepenuhnya gratis. Anda dapat mengunduh video dalam berbagai format dan kualitas tanpa biaya apa pun.",
    "faq2_q": "Format video apa saja yang didukung?",
    "faq2_a": "Kami mendukung berbagai format termasuk MP4, WebM untuk video, dan MP3 untuk audio. Anda dapat memilih dari berbagai opsi kualitas mulai dari 360p hingga 4K (jika tersedia).",
    "faq3_q": "Apakah mengunduh video YouTube legal?",
    "faq3_a": "Mengunduh video untuk penggunaan pribadi umumnya dapat diterima. Namun, harap hormati hukum hak cipta dan hak pencipta konten. Jangan distribusikan atau gunakan konten yang diunduh untuk tujuan komersial tanpa otorisasi yang tepat.",
    "faq4_q": "Bagaimana cara mengunduh video YouTube?",
    "faq4_a": "1. Salin URL video YouTube<br>2. Tempelkan di kotak masukan di atas<br>3. Tunggu hingga format yang tersedia dimuat<br>4. Pilih format dan kualitas yang Anda inginkan<br>5. Klik tombol unduh",
    "faq5_q": "Apakah ada batasan unduhan?",
    "faq5_a": "Tidak ada batasan ketat pada unduhan. Namun, kami merekomendasikan penggunaan yang wajar untuk memastikan layanan tetap tersedia untuk semua orang. File yang sangat besar mungkin memerlukan waktu lebih lama untuk diproses.",
    "copyright": "© 2025 YTGrab. Hak cipta dilindungi.",
    "privacy_policy": "Kebijakan Privasi",
    "terms": "Syarat",
    "contact": "Kontak",
    "url_error": "Harap masukkan URL YouTube yang valid"
  },
  "it": {
    "title": "Scarica video YouTube facilmente",
    "description": "Scarica video YouTube in formati MP4 e MP3 facilmente, senza pubblicità e gratuitamente.",
    "brand": "YTGrab",
    "faq": "Domande Frequenti",
    "language": "Italiano",
    "subtitle": "Scarica video e audio in più formati in modo rapido e semplice",
    "placeholder": "Incolla il link di YouTube qui...",
    "download_button": "Scarica",
    "choose_format": "Scegli Formato",
    "back": "Indietro",
    "support": "Supportiamo il download di video da YouTube in tutti i formati e qualità disponibili.",
    "format": "Formato",
    "size": "Dimensione",
    "download": "Scarica",
    "instant_download": "Download Istantaneo",
    "instant_download_desc": "Ottieni i tuoi video in pochi secondi con i nostri server ad alta velocità",
    "multiple_formats": "Formati Multipli",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K e molti altri formati disponibili",
    "easy_to_use": "Facile da Usare",
    "easy_to_use_desc": "Incolla il link e scarica - nessuna registrazione richiesta",
    "how_it_works": "Come Funziona",
    "step1_title": "Copia URL",
    "step1_desc": "Copia il link del video YouTube",
    "step2_title": "Incolla Link",
    "step2_desc": "Incolla nella casella sopra",
    "step3_title": "Scegli Formato",
    "step3_desc": "Seleziona qualità/formato",
    "step4_title": "Scarica",
    "step4_desc": "Ottieni il tuo file istantaneamente",
    "faq_title": "Domande Frequenti",
    "faq1_q": "È gratis scaricare video YouTube?",
    "faq1_a": "Sì, il nostro servizio è completamente gratuito. Puoi scaricare video in vari formati e qualità senza alcun costo.",
    "faq2_q": "Quali formati video sono supportati?",
    "faq2_a": "Supportiamo vari formati, inclusi MP4, WebM per i video e MP3 per l’audio. Puoi scegliere tra diverse opzioni di qualità, da 360p a 4K (quando disponibile).",
    "faq3_q": "È legale scaricare video YouTube?",
    "faq3_a": "Scaricare video per uso personale è generalmente accettabile. Tuttavia, rispetta le leggi sul copyright e i diritti dei creatori di contenuti. Non distribuire o utilizzare i contenuti scaricati per scopi commerciali senza autorizzazione appropriata.",
    "faq4_q": "Come scarico un video YouTube?",
    "faq4_a": "1. Copia l’URL del video YouTube<br>2. Incollalo nella casella di input sopra<br>3. Attendi che i formati disponibili vengano caricati<br>4. Scegli il formato e la qualità preferiti<br>5. Clicca sul pulsante di download",
    "faq5_q": "Ci sono limiti di download?",
    "faq5_a": "Non ci sono limiti rigidi sui download. Tuttavia, raccomandiamo un uso ragionevole per garantire che il servizio rimanga disponibile per tutti. I file molto grandi potrebbero richiedere più tempo per l’elaborazione.",
    "copyright": "© 2025 YTGrab. Tutti i diritti riservati.",
    "privacy_policy": "Informativa sulla Privacy",
    "terms": "Termini",
    "contact": "Contatto",
    "url_error": "Inserisci un URL YouTube valido"
  },
  "ja": {
    "title": "YouTube動画を簡単にダウンロード",
    "description": "YouTube動画をMP4およびMP3形式で簡単に、広告なしで無料でダウンロード。",
    "brand": "YTGrab",
    "faq": "よくある質問",
    "language": "日本語",
    "subtitle": "複数の形式でビデオとオーディオを素早く簡単にダウンロード",
    "placeholder": "YouTubeリンクをここに貼り付け...",
    "download_button": "ダウンロード",
    "choose_format": "形式を選択",
    "back": "戻る",
    "support": "YouTubeからすべての利用可能な形式と品質で動画のダウンロードをサポートしています。",
    "format": "形式",
    "size": "サイズ",
    "download": "ダウンロード",
    "instant_download": "即時ダウンロード",
    "instant_download_desc": "高速サーバーで数秒で動画を取得",
    "multiple_formats": "複数の形式",
    "multiple_formats_desc": "MP4、MP3、1080p、4Kなど多くの形式が利用可能",
    "easy_to_use": "使いやすい",
    "easy_to_use_desc": "リンクを貼り付けてダウンロード - 登録不要",
    "how_it_works": "仕組み",
    "step1_title": "URLをコピー",
    "step1_desc": "YouTube動画のリンクをコピー",
    "step2_title": "リンクを貼り付け",
    "step2_desc": "上のボックスに貼り付け",
    "step3_title": "形式を選択",
    "step3_desc": "品質/形式を選択",
    "step4_title": "ダウンロード",
    "step4_desc": "ファイル即時取得",
    "faq_title": "よくある質問",
    "faq1_q": "YouTube動画のダウンロードは無料ですか？",
    "faq1_a": "はい、当社のサービスは完全に無料です。さまざまな形式と品質で動画を無料でダウンロードできます。",
    "faq2_q": "サポートされているビデオ形式は何ですか？",
    "faq2_a": "MP4、WebM（ビデオ用）、MP3（オーディオ用）など、さまざまな形式をサポートしています。360pから4Kまでのさまざまな品質オプションから選択できます（利用可能な場合）。",
    "faq3_q": "YouTube動画のダウンロードは合法ですか？",
    "faq3_a": "個人使用のための動画ダウンロードは一般的に許容されます。ただし、著作権法とコンテンツ作成者の権利を尊重してください。適切な許可なくダウンロードしたコンテンツを配布したり商業目的で使用したりしないでください。",
    "faq4_q": "YouTube動画をダウンロードする方法は？",
    "faq4_a": "1. YouTube動画のURLをコピー<br>2. 上の入力ボックスに貼り付け<br>3. 利用可能な形式がロードされるのを待つ<br>4. 希望する形式と品質を選択<br>5. ダウンロードボタンをクリック",
    "faq5_q": "ダウンロード制限はありますか？",
    "faq5_a": "ダウンロードに厳格な制限はありません。ただし、サービスが全員に利用可能であることを確保するために、合理的な使用をお勧めします。非常に大きなファイルは処理に時間がかかる場合があります。",
    "copyright": "© 2025 YTGrab。全権利を保有。",
    "privacy_policy": "プライバシーポリシー",
    "terms": "利用規約",
    "contact": "お問い合わせ",
    "url_error": "有効なYouTube URLを入力してください"
  },
  "ko": {
    "title": "YouTube 동영상을 쉽게 다운로드",
    "description": "YouTube 동영상을 MP4 및 MP3 형식으로 쉽게, 광고 없이 무료로 다운로드하세요.",
    "brand": "YTGrab",
    "faq": "자주 묻는 질문",
    "language": "한국어",
    "subtitle": "다양한 형식으로 비디오와 오디오를 빠르고 쉽게 다운로드",
    "placeholder": "여기에 YouTube 링크를 붙여넣으세요...",
    "download_button": "다운로드",
    "choose_format": "형식 선택",
    "back": "뒤로",
    "support": "YouTube에서 사용 가능한 모든 형식과 품질로 동영상 다운로드를 지원합니다.",
    "format": "형식",
    "size": "크기",
    "download": "다운로드",
    "instant_download": "즉시 다운로드",
    "instant_download_desc": "고속 서버로 몇 초 만에 동영상을 받아보세요",
    "multiple_formats": "다양한 형식",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K 등 다양한 형식이 제공됩니다",
    "easy_to_use": "사용하기 쉬움",
    "easy_to_use_desc": "링크를 붙여넣고 다운로드하세요 - 등록이 필요 없습니다",
    "how_it_works": "작동 방식",
    "step1_title": "URL 복사",
    "step1_desc": "YouTube 동영상 링크를 복사하세요",
    "step2_title": "링크 붙여넣기",
    "step2_desc": "위의 상자에 붙여넣기",
    "step3_title": "형식 선택",
    "step3_desc": "품질/형식 선택",
    "step4_title": "다운로드",
    "step4_desc": "파일을 즉시 받아보세요",
    "faq_title": "자주 묻는 질문",
    "faq1_q": "YouTube 동영상 다운로드는 무료인가요?",
    "faq1_a": "네, 저희 서비스는 완전히 무료입니다. 다양한 형식과 품질로 동영상을 무료로 다운로드할 수 있습니다.",
    "faq2_q": "지원되는 비디오 형식은 무엇인가요?",
    "faq2_a": "MP4, WebM(비디오용), MP3(오디오용) 등 다양한 형식을 지원합니다. 360p에서 4K까지 다양한 품질 옵션 중 선택할 수 있습니다(사용 가능한 경우).",
    "faq3_q": "YouTube 동영상 다운로드는 합법적인가요?",
    "faq3_a": "개인적인 용도로 동영상을 다운로드하는 것은 일반적으로 허용됩니다. 하지만 저작권법과 콘텐츠 제작자의 권리를 존중해 주세요. 적절한 허가 없이 다운로드한 콘텐츠를 배포하거나 상업적 목적으로 사용하지 마세요.",
    "faq4_q": "YouTube 동영상을 어떻게 다운로드하나요?",
    "faq4_a": "1. YouTube 동영상 URL을 복사하세요<br>2. 위의 입력 상자에 붙여넣으세요<br>3. 사용 가능한 형식이 로드될 때까지 기다리세요<br>4. 원하는 형식과 품질을 선택하세요<br>5. 다운로드 버튼을 클릭하세요",
    "faq5_q": "다운로드 제한이 있나요?",
    "faq5_a": "다운로드에 엄격한 제한은 없습니다. 하지만 모든 사람이 서비스를 이용할 수 있도록 합리적인 사용을 권장합니다. 매우 큰 파일은 처리에 시간이 더 걸릴 수 있습니다.",
    "copyright": "© 2025 YTGrab. 모든 권리 보유.",
    "privacy_policy": "개인정보 보호정책",
    "terms": "이용약관",
    "contact": "연락처",
    "url_error": "유효한 YouTube URL을 입력해 주세요"
  },
  "ms": {
    "title": "Muat turun Video YouTube dengan Mudah",
    "description": "Muat turun video YouTube dalam format MP4 dan MP3 dengan mudah, tanpa iklan dan percuma.",
    "brand": "YTGrab",
    "faq": "Soalan Lazim",
    "language": "Bahasa Melayu",
    "subtitle": "Muat turun video dan audio dalam pelbagai format dengan cepat dan mudah",
    "placeholder": "Tampal pautan YouTube di sini...",
    "download_button": "Muat turun",
    "choose_format": "Pilih Format",
    "back": "Kembali",
    "support": "Kami menyokong muat turun video dari YouTube dalam semua format dan kualiti yang tersedia.",
    "format": "Format",
    "size": "Saiz",
    "download": "Muat turun",
    "instant_download": "Muat Turun Segera",
    "instant_download_desc": "Dapatkan video anda dalam beberapa saat dengan pelayan berkelajuan tinggi kami",
    "multiple_formats": "Pelbagai Format",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K, dan banyak lagi format yang tersedia",
    "easy_to_use": "Mudah Digunakan",
    "easy_to_use_desc": "Tampal pautan dan muat turun - tiada pendaftaran diperlukan",
    "how_it_works": "Cara Ia Berfungsi",
    "step1_title": "Salin URL",
    "step1_desc": "Salin pautan video YouTube",
    "step2_title": "Tampal Pautan",
    "step2_desc": "Tampal di kotak di atas",
    "step3_title": "Pilih Format",
    "step3_desc": "Pilih kualiti/format",
    "step4_title": "Muat turun",
    "step4_desc": "Dapatkan fail anda serta-merta",
    "faq_title": "Soalan Lazim",
    "faq1_q": "Adakah muat turun video YouTube percuma?",
    "faq1_a": "Ya, perkhidmatan kami adalah percuma sepenuhnya. Anda boleh memuat turun video dalam pelbagai format dan kualiti tanpa sebarang kos.",
    "faq2_q": "Format video apa yang disokong?",
    "faq2_a": "Kami menyokong pelbagai format termasuk MP4, WebM untuk video, dan MP3 untuk audio. Anda boleh memilih daripada pelbagai pilihan kualiti dari 360p hingga 4K (jika tersedia).",
    "faq3_q": "Adakah muat turun video YouTube sah?",
    "faq3_a": "Memuat turun video untuk kegunaan peribadi secara amnya boleh diterima. Walau bagaimanapun, sila hormati undang-undang hak cipta dan hak pencipta kandungan. Jangan edarkan atau gunakan kandungan yang dimuat turun untuk tujuan komersial tanpa kebenaran yang sewajarnya.",
    "faq4_q": "Bagaimana saya memuat turun video YouTube?",
    "faq4_a": "1. Salin URL video YouTube<br>2. Tampal di kotak input di atas<br>3. Tunggu sehingga format yang tersedia dimuatkan<br>4. Pilih format dan kualiti yang anda inginkan<br>5. Klik butang muat turun",
    "faq5_q": "Adakah terdapat had muat turun?",
    "faq5_a": "Tiada had ketat untuk muat turun. Walau bagaimanapun, kami mengesyorkan penggunaan yang munasabah untuk memastikan perkhidmatan kekal tersedia untuk semua. Fail yang sangat besar mungkin mengambil masa lebih lama untuk diproses.",
    "copyright": "© 2025 YTGrab. Hak cipta terpelihara.",
    "privacy_policy": "Dasar Privasi",
    "terms": "Terma",
    "contact": "Hubungi",
    "url_error": "Sila masukkan URL YouTube yang sah"
  },
  "nl": {
    "title": "Download YouTube-video’s eenvoudig",
    "description": "Download YouTube-video’s in MP4- en MP3-formaten eenvoudig, zonder advertenties en gratis.",
    "brand": "YTGrab",
    "faq": "Veelgestelde Vragen",
    "language": "Nederlands",
    "subtitle": "Download video’s en audio in meerdere formaten snel en eenvoudig",
    "placeholder": "Plak de YouTube-link hier...",
    "download_button": "Downloaden",
    "choose_format": "Kies Formaat",
    "back": "Terug",
    "support": "Wij ondersteunen het downloaden van video’s van YouTube in alle beschikbare formaten en kwaliteiten.",
    "format": "Formaat",
    "size": "Grootte",
    "download": "Downloaden",
    "instant_download": "Direct Downloaden",
    "instant_download_desc": "Krijg je video’s binnen enkele seconden met onze snelle servers",
    "multiple_formats": "Meerdere Formaten",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K en nog veel meer formaten beschikbaar",
    "easy_to_use": "Eenvoudig in Gebruik",
    "easy_to_use_desc": "Plak de link en download - geen registratie vereist",
    "how_it_works": "Hoe Het Werkt",
    "step1_title": "URL Kopiëren",
    "step1_desc": "Kopieer de YouTube-video-link",
    "step2_title": "Link Plakken",
    "step2_desc": "Plak in het vak hierboven",
    "step3_title": "Formaat Kiezen",
    "step3_desc": "Selecteer kwaliteit/formaat",
    "step4_title": "Downloaden",
    "step4_desc": "Krijg je bestand direct",
    "faq_title": "Veelgestelde Vragen",
    "faq1_q": "Is het gratis om YouTube-video’s te downloaden?",
    "faq1_a": "Ja, onze dienst is volledig gratis. Je kunt video’s in verschillende formaten en kwaliteiten downloaden zonder kosten.",
    "faq2_q": "Welke videoformaten worden ondersteund?",
    "faq2_a": "We ondersteunen verschillende formaten, waaronder MP4, WebM voor video en MP3 voor audio. Je kunt kiezen uit verschillende kwaliteitsopties, van 360p tot 4K (indien beschikbaar).",
    "faq3_q": "Is het legaal om YouTube-video’s te downloaden?",
    "faq3_a": "Het downloaden van video’s voor persoonlijk gebruik is over het algemeen acceptabel. Respecteer echter de auteursrechtwetten en de rechten van contentmakers. Verspreid of gebruik gedownloade inhoud niet voor commerciële doeleinden zonder de juiste toestemming.",
    "faq4_q": "Hoe download ik een YouTube-video?",
    "faq4_a": "1. Kopieer de URL van de YouTube-video<br>2. Plak deze in het invoerveld hierboven<br>3. Wacht tot de beschikbare formaten zijn geladen<br>4. Kies je gewenste formaat en kwaliteit<br>5. Klik op de downloadknop",
    "faq5_q": "Zijn er downloadlimieten?",
    "faq5_a": "Er zijn geen strikte downloadlimieten. We raden echter redelijk gebruik aan om ervoor te zorgen dat de dienst voor iedereen beschikbaar blijft. Zeer grote bestanden kunnen langer duren om te verwerken.",
    "copyright": "© 2025 YTGrab. Alle rechten voorbehouden.",
    "privacy_policy": "Privacybeleid",
    "terms": "Voorwaarden",
    "contact": "Contact",
    "url_error": "Voer een geldige YouTube-URL in"
  },
    "pl": {
    "title": "Pobieraj filmy z YouTube łatwo",
    "description": "Pobieraj filmy z YouTube w formatach MP4 i MP3 łatwo, bez reklam i za darmo.",
    "brand": "YTGrab",
    "faq": "Często Zadawane Pytania",
    "language": "Polski",
    "subtitle": "Pobieraj filmy i audio w wielu formatach szybko i łatwo",
    "placeholder": "Wklej link do YouTube tutaj...",
    "download_button": "Pobierz",
    "choose_format": "Wybierz Format",
    "back": "Wstecz",
    "support": "Wspieramy pobieranie filmów z YouTube we wszystkich dostępnych formatach i jakościach.",
    "format": "Format",
    "size": "Rozmiar",
    "download": "Pobierz",
    "instant_download": "Natychmiastowe Pobieranie",
    "instant_download_desc": "Pobierz swoje filmy w kilka sekund dzięki naszym szybkim serwerom",
    "multiple_formats": "Wiele Formatów",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K i wiele innych formatów dostępnych",
    "easy_to_use": "Łatwy w Użyciu",
    "easy_to_use_desc": "Wklej link i pobierz - nie wymaga rejestracji",
    "how_it_works": "Jak To Działa",
    "step1_title": "Skopiuj URL",
    "step1_desc": "Skopiuj link do filmu z YouTube",
    "step2_title": "Wklej Link",
    "step2_desc": "Wklej do pola powyżej",
    "step3_title": "Wybierz Format",
    "step3_desc": "Wybierz jakość/format",
    "step4_title": "Pobierz",
    "step4_desc": "Odbierz swój plik natychmiast",
    "faq_title": "Często Zadawane Pytania",
    "faq1_q": "Czy pobieranie filmów z YouTube jest darmowe?",
    "faq1_a": "Tak, nasza usługa jest całkowicie darmowa. Możesz pobierać filmy w różnych formatach i jakościach bez żadnych kosztów.",
    "faq2_q": "Jakie formaty wideo są obsługiwane?",
    "faq2_a": "Obsługujemy różne formaty, w tym MP4, WebM dla wideo i MP3 dla audio. Możesz wybrać spośród różnych opcji jakości, od 360p do 4K (jeśli dostępne).",
    "faq3_q": "Czy pobieranie filmów z YouTube jest legalne?",
    "faq3_a": "Pobieranie filmów do użytku osobistego jest ogólnie akceptowalne. Prosimy jednak szanować prawa autorskie i prawa twórców treści. Nie rozpowszechniaj ani nie używaj pobranych treści do celów komercyjnych bez odpowiedniego zezwolenia.",
    "faq4_q": "Jak pobrać film z YouTube?",
    "faq4_a": "1. Skopiuj URL filmu z YouTube<br>2. Wklej go do pola wprowadzania powyżej<br>3. Poczekaj, aż dostępne formaty się załadują<br>4. Wybierz preferowany format i jakość<br>5. Kliknij przycisk pobierania",
    "faq5_q": "Czy są jakieś limity pobierania?",
    "faq5_a": "Nie ma ścisłych limitów pobierania. Zalecamy jednak rozsądne korzystanie, aby zapewnić dostępność usługi dla wszystkich. Bardzo duże pliki mogą wymagać dłuższego przetwarzania.",
    "copyright": "© 2025 YTGrab. Wszelkie prawa zastrzeżone.",
    "privacy_policy": "Polityka Prywatności",
    "terms": "Warunki",
    "contact": "Kontakt",
    "url_error": "Proszę wprowadzić prawidłowy adres URL YouTube"
  },
  "pt": {
    "title": "Baixe Vídeos do YouTube Facilmente",
    "description": "Baixe vídeos do YouTube em formatos MP4 e MP3 facilmente, sem anúncios e de graça.",
    "brand": "YTGrab",
    "faq": "Perguntas Frequentes",
    "language": "Português",
    "subtitle": "Baixe vídeos e áudios em vários formatos de forma rápida e fácil",
    "placeholder": "Cole o link do YouTube aqui...",
    "download_button": "Baixar",
    "choose_format": "Escolher Formato",
    "back": "Voltar",
    "support": "Suportamos o download de vídeos do YouTube em todos os formatos e qualidades disponíveis.",
    "format": "Formato",
    "size": "Tamanho",
    "download": "Baixar",
    "instant_download": "Download Instantâneo",
    "instant_download_desc": "Obtenha seus vídeos em segundos com nossos servidores de alta velocidade",
    "multiple_formats": "Vários Formatos",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K e muitos outros formatos disponíveis",
    "easy_to_use": "Fácil de Usar",
    "easy_to_use_desc": "Cole o link e baixe - sem necessidade de registro",
    "how_it_works": "Como Funciona",
    "step1_title": "Copiar URL",
    "step1_desc": "Copie o link do vídeo do YouTube",
    "step2_title": "Colar Link",
    "step2_desc": "Cole na caixa acima",
    "step3_title": "Escolher Formato",
    "step3_desc": "Selecione qualidade/formato",
    "step4_title": "Baixar",
    "step4_desc": "Obtenha seu arquivo instantaneamente",
    "faq_title": "Perguntas Frequentes",
    "faq1_q": "É grátis baixar vídeos do YouTube?",
    "faq1_a": "Sim, nosso serviço é totalmente gratuito. Você pode baixar vídeos em vários formatos e qualidades sem nenhum custo.",
    "faq2_q": "Quais formatos de vídeo são suportados?",
    "faq2_a": "Suportamos vários formatos, incluindo MP4, WebM para vídeo e MP3 para áudio. Você pode escolher entre diferentes opções de qualidade, de 360p a 4K (quando disponível).",
    "faq3_q": "É legal baixar vídeos do YouTube?",
    "faq3_a": "Baixar vídeos para uso pessoal é geralmente aceitável. No entanto, respeite as leis de direitos autorais e os direitos dos criadores de conteúdo. Não distribua ou use o conteúdo baixado para fins comerciais sem autorização adequada.",
    "faq4_q": "Como baixo um vídeo do YouTube?",
    "faq4_a": "1. Copie o URL do vídeo do YouTube<br>2. Cole-o na caixa de entrada acima<br>3. Aguarde o carregamento dos formatos disponíveis<br>4. Escolha o formato e qualidade preferidos<br>5. Clique no botão de download",
    "faq5_q": "Há limites de download?",
    "faq5_a": "Não há limites rígidos para downloads. No entanto, recomendamos uso moderado para garantir que o serviço permaneça disponível para todos. Arquivos muito grandes podem levar mais tempo para serem processados.",
    "copyright": "© 2025 YTGrab. Todos os direitos reservados.",
    "privacy_policy": "Política de Privacidade",
    "terms": "Termos",
    "contact": "Contato",
    "url_error": "Por favor, insira um URL válido do YouTube"
  },
  "ro": {
    "title": "Descărcați videoclipuri YouTube ușor",
    "description": "Descărcați videoclipuri YouTube în formatele MP4 și MP3 ușor, fără reclame și gratuit.",
    "brand": "YTGrab",
    "faq": "Întrebări Frecvente",
    "language": "Română",
    "subtitle": "Descărcați videoclipuri și audio în mai multe formate rapid și ușor",
    "placeholder": "Lipiți link-ul YouTube aici...",
    "download_button": "Descarcă",
    "choose_format": "Alege Formatul",
    "back": "Înapoi",
    "support": "Susținem descărcarea videoclipurilor de pe YouTube în toate formatele și calitățile disponibile.",
    "format": "Format",
    "size": "Dimensiune",
    "download": "Descarcă",
    "instant_download": "Descărcare Instantanee",
    "instant_download_desc": "Obțineți videoclipurile în câteva secunde cu serverele noastre de mare viteză",
    "multiple_formats": "Formate Multiple",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K și multe alte formate disponibile",
    "easy_to_use": "Ușor de Utilizat",
    "easy_to_use_desc": "Lipiți link-ul și descărcați - nu este necesară înregistrarea",
    "how_it_works": "Cum Funcționează",
    "step1_title": "Copiază URL",
    "step1_desc": "Copiază link-ul videoclipului YouTube",
    "step2_title": "Lipește Link-ul",
    "step2_desc": "Lipește în caseta de mai sus",
    "step3_title": "Alege Formatul",
    "step3_desc": "Selectează calitatea/formatul",
    "step4_title": "Descarcă",
    "step4_desc": "Obține fișierul instantaneu",
    "faq_title": "Întrebări Frecvente",
    "faq1_q": "Este gratuit să descarci videoclipuri YouTube?",
    "faq1_a": "Da, serviciul nostru este complet gratuit. Puteți descărca videoclipuri în diverse formate și calități fără niciun cost.",
    "faq2_q": "Ce formate video sunt suportate?",
    "faq2_a": "Susținem diverse formate, inclusiv MP4, WebM pentru video și MP3 pentru audio. Puteți alege dintre diferite opțiuni de calitate, de la 360p la 4K (când sunt disponibile).",
    "faq3_q": "Este legal să descarci videoclipuri YouTube?",
    "faq3_a": "Descărcarea videoclipurilor pentru uz personal este, în general, acceptabilă. Cu toate acestea, vă rugăm să respectați legile privind drepturile de autor și drepturile creatorilor de conținut. Nu distribuiți sau folosiți conținutul descărcat în scopuri comerciale fără autorizație corespunzătoare.",
    "faq4_q": "Cum descarc un videoclip YouTube?",
    "faq4_a": "1. Copiază URL-ul videoclipului YouTube<br>2. Lipește-l în caseta de introducere de mai sus<br>3. Așteaptă să se încarce formatele disponibile<br>4. Alege formatul și calitatea preferate<br>5. Apasă butonul de descărcare",
    "faq5_q": "Există limite de descărcare?",
    "faq5_a": "Nu există limite stricte pentru descărcări. Cu toate acestea, recomandăm utilizarea rezonabilă pentru a asigura disponibilitatea serviciului pentru toți. Fișierele foarte mari pot necesita mai mult timp pentru procesare.",
    "copyright": "© 2025 YTGrab. Toate drepturile rezervate.",
    "privacy_policy": "Politica de Confidențialitate",
    "terms": "Termeni",
    "contact": "Contact",
    "url_error": "Vă rugăm să introduceți un URL YouTube valid"
  },
  "ru": {
    "title": "Скачивайте видео с YouTube легко",
    "description": "Скачивайте видео с YouTube в форматах MP4 и MP3 легко, без рекламы и бесплатно.",
    "brand": "YTGrab",
    "faq": "Часто задаваемые вопросы",
    "language": "Русский",
    "subtitle": "Скачивайте видео и аудио в различных форматах быстро и легко",
    "placeholder": "Вставьте ссылку на YouTube здесь...",
    "download_button": "Скачать",
    "choose_format": "Выбрать формат",
    "back": "Назад",
    "support": "Мы поддерживаем скачивание видео с YouTube во всех доступных форматах и качествах.",
    "format": "Формат",
    "size": "Размер",
    "download": "Скачать",
    "instant_download": "Мгновенная загрузка",
    "instant_download_desc": "Получите ваши видео за секунды с нашими высокоскоростными серверами",
    "multiple_formats": "Различные форматы",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K и многие другие форматы доступны",
    "easy_to_use": "Простота использования",
    "easy_to_use_desc": "Вставьте ссылку и скачайте - регистрация не требуется",
    "how_it_works": "Как это работает",
    "step1_title": "Скопировать URL",
    "step1_desc": "Скопируйте ссылку на видео YouTube",
    "step2_title": "Вставить ссылку",
    "step2_desc": "Вставьте в поле выше",
    "step3_title": "Выбрать формат",
    "step3_desc": "Выберите качество/формат",
    "step4_title": "Скачать",
    "step4_desc": "Получите ваш файл мгновенно",
    "faq_title": "Часто задаваемые вопросы",
    "faq1_q": "Бесплатно ли скачивать видео с YouTube?",
    "faq1_a": "Да, наш сервис полностью бесплатный. Вы можете скачивать видео в различных форматах и качествах без каких-либо затрат.",
    "faq2_q": "Какие форматы видео поддерживаются?",
    "faq2_a": "Мы поддерживаем различные форматы, включая MP4, WebM для видео и MP3 для аудио. Вы можете выбирать из разных вариантов качества от 360p до 4K (при наличии).",
    "faq3_q": "Законно ли скачивать видео с YouTube?",
    "faq3_a": "Скачивание видео для личного использования, как правило, допустимо. Однако, пожалуйста, уважайте законы об авторском праве и права создателей контента. Не распространяйте и не используйте скачанный контент в коммерческих целях без соответствующего разрешения.",
    "faq4_q": "Как скачать видео с YouTube?",
    "faq4_a": "1. Скопируйте URL видео с YouTube<br>2. Вставьте его в поле ввода выше<br>3. Дождитесь загрузки доступных форматов<br>4. Выберите предпочитаемый формат и качество<br>5. Нажмите кнопку скачивания",
    "faq5_q": "Есть ли ограничения на скачивание?",
    "faq5_a": "Жестких ограничений на скачивание нет. Однако мы рекомендуем разумное использование, чтобы сервис оставался доступным для всех. Очень большие файлы могут требовать больше времени на обработку.",
    "copyright": "© 2025 YTGrab. Все права защищены.",
    "privacy_policy": "Политика конфиденциальности",
    "terms": "Условия",
    "contact": "Контакты",
    "url_error": "Пожалуйста, введите действительный URL YouTube"
  },
  "sk": {
    "title": "Sťahujte videá z YouTube jednoducho",
    "description": "Sťahujte videá z YouTube vo formátoch MP4 a MP3 jednoducho, bez reklám a zadarmo.",
    "brand": "YTGrab",
    "faq": "Často kladené otázky",
    "language": "Slovenčina",
    "subtitle": "Sťahujte videá a zvuk vo viacerých formátoch rýchlo a jednoducho",
    "placeholder": "Sem vložte odkaz na YouTube...",
    "download_button": "Stiahnuť",
    "choose_format": "Vybrať formát",
    "back": "Späť",
    "support": "Podporujeme sťahovanie videí z YouTube vo všetkých dostupných formátoch a kvalitách.",
    "format": "Formát",
    "size": "Veľkosť",
    "download": "Stiahnuť",
    "instant_download": "Okamžité sťahovanie",
    "instant_download_desc": "Získajte svoje videá v priebehu sekúnd s našimi vysokorýchlostnými servermi",
    "multiple_formats": "Viacero formátov",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K a mnoho ďalších formátov dostupných",
    "easy_to_use": "Jednoduché použitie",
    "easy_to_use_desc": "Vložte odkaz a stiahnite – nie je potrebná registrácia",
    "how_it_works": "Ako to funguje",
    "step1_title": "Kopírovať URL",
    "step1_desc": "Skopírujte odkaz na video z YouTube",
    "step2_title": "Vložiť odkaz",
    "step2_desc": "Vložte do poľa vyššie",
    "step3_title": "Vybrať formát",
    "step3_desc": "Vyberte kvalitu/formát",
    "step4_title": "Stiahnuť",
    "step4_desc": "Získajte svoj súbor okamžite",
    "faq_title": "Často kladené otázky",
    "faq1_q": "Je sťahovanie videí z YouTube zadarmo?",
    "faq1_a": "Áno, naša služba je úplne zadarmo. Môžete sťahovať videá v rôznych formátoch a kvalitách bez akýchkoľvek nákladov.",
    "faq2_q": "Aké formáty videa sú podporované?",
    "faq2_a": "Podporujeme rôzne formáty vrátane MP4, WebM pre video a MP3 pre zvuk. Môžete si vybrať z rôznych možností kvality od 360p po 4K (ak sú k dispozícii).",
    "faq3_q": "Je sťahovanie videí z YouTube legálne?",
    "faq3_a": "Sťahovanie videí na osobné použitie je vo všeobecnosti akceptovateľné. Prosím, rešpektujte však zákony o autorských právach a práva tvorcov obsahu. Nerozširujte ani nepoužívajte stiahnutý obsah na komerčné účely bez náležitého povolenia.",
    "faq4_q": "Ako stiahnem video z YouTube?",
    "faq4_a": "1. Skopírujte URL videa z YouTube<br>2. Vložte ho do vstupného poľa vyššie<br>3. Počkajte, kým sa načítajú dostupné formáty<br>4. Vyberte preferovaný formát a kvalitu<br>5. Kliknite na tlačidlo sťahovania",
    "faq5_q": "Sú nejaké obmedzenia na sťahovanie?",
    "faq5_a": "Neexistujú žiadne prísne obmedzenia na sťahovanie. Odporúčame však rozumné používanie, aby služba zostala dostupná pre všetkých. Veľmi veľké súbory môžu vyžadovať dlhší čas na spracovanie.",
    "copyright": "© 2025 YTGrab. Všetky práva vyhradené.",
    "privacy_policy": "Zásady ochrany osobných údajov",
    "terms": "Podmienky",
    "contact": "Kontakt",
    "url_error": "Zadajte platnú adresu URL YouTube"
  },
  "sr": {
    "title": "Преузмите Јутјуб видео записе лако",
    "description": "Преузмите Јутјуб видео записе у МП4 и МП3 форматима лако, без реклама и бесплатно.",
    "brand": "YTGrab",
    "faq": "Често Постављана Питања",
    "language": "Српски",
    "subtitle": "Преузмите видео и аудио у више формата брзо и лако",
    "placeholder": "Овде налепите Јутјуб линк...",
    "download_button": "Преузми",
    "choose_format": "Изабери Формат",
    "back": "Назад",
    "support": "Подржавамо преузимање видео записа са Јутјуба у свим доступним форматима и квалитетима.",
    "format": "Формат",
    "size": "Величина",
    "download": "Преузми",
    "instant_download": "Тренутно Преузимање",
    "instant_download_desc": "Добијте своје видео записе за неколико секунди са нашим серверима велике брзине",
    "multiple_formats": "Више Формата",
    "multiple_formats_desc": "МП4, МП3, 1080п, 4К и многи други формати доступни",
    "easy_to_use": "Лако за Употребу",
    "easy_to_use_desc": "Налепите линк и преузмите - регистрација није потребна",
    "how_it_works": "Како Функционише",
    "step1_title": "Копирај УРЛ",
    "step1_desc": "Копирајте линк Јутјуб видеа",
    "step2_title": "Налепи Линк",
    "step2_desc": "Налепите у поље изнад",
    "step3_title": "Изабери Формат",
    "step3_desc": "Изаберите квалитет/формат",
    "step4_title": "Преузми",
    "step4_desc": "Добијте ваш фајл тренутно",
    "faq_title": "Често Постављана Питања",
    "faq1_q": "Да ли је бесплатно преузимање Јутјуб видео записа?",
    "faq1_a": "Да, наша услуга је потпуно бесплатна. Можете преузимати видео записе у различитим форматима и квалитетима без икаквих трошкова.",
    "faq2_q": "Који формати видеа су подржани?",
    "faq2_a": "Подржавамо различите формате, укључујући МП4, ВебМ за видео и МП3 за аудио. Можете бирати између различитих опција квалитета од 360п до 4К (када је доступно).",
    "faq3_q": "Да ли је легално преузимање Јутјуб видео записа?",
    "faq3_a": "Преузимање видео записа за личну употребу је углавном прихватљиво. Међутим, молимо вас да поштујете законе о ауторским правима и права креатора садржаја. Не дистрибуирајте нити користите преузети садржај у комерцијалне сврхе без одговарајућег одобрења.",
    "faq4_q": "Како да преузмем Јутјуб видео?",
    "faq4_a": "1. Копирајте УРЛ Јутјуб видеа<br>2. Налепите га у поље за унос изнад<br>3. Сачекајте да се учитају доступни формати<br>4. Изаберите жељени формат и квалитет<br>5. Кликните на дугме за преузимање",
    "faq5_q": "Постоје ли ограничења за преузимање?",
    "faq5_a": "Не постоје строга ограничења за преузимање. Међутим, препоручујемо разумну употребу како би услуга остала доступна свима. Веома велики фајлови могу захтевати више времена за обраду.",
    "copyright": "© 2025 YTGrab. Сва права задржана.",
    "privacy_policy": "Политика Приватности",
    "terms": "Услови",
    "contact": "Контакт",
    "url_error": "Унесите важећи Јутјуб УРЛ"
  },
  "sv": {
    "title": "Ladda ner YouTube-videor enkelt",
    "description": "Ladda ner YouTube-videor i MP4- och MP3-format enkelt, utan annonser och gratis.",
    "brand": "YTGrab",
    "faq": "Vanliga Frågor",
    "language": "Svenska",
    "subtitle": "Ladda ner videor och ljud i flera format snabbt och enkelt",
    "placeholder": "Klistra in YouTube-länken här...",
    "download_button": "Ladda ner",
    "choose_format": "Välj Format",
    "back": "Tillbaka",
    "support": "Vi stöder nedladdning av videor från YouTube i alla tillgängliga format och kvaliteter.",
    "format": "Format",
    "size": "Storlek",
    "download": "Ladda ner",
    "instant_download": "Omedelbar Nedladdning",
    "instant_download_desc": "Få dina videor på några sekunder med våra höghastighetsservrar",
    "multiple_formats": "Flera Format",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K och många fler format tillgängliga",
    "easy_to_use": "Lätt att Använda",
    "easy_to_use_desc": "Klistra in länken och ladda ner - ingen registrering krävs",
    "how_it_works": "Så Fungerar Det",
    "step1_title": "Kopiera URL",
    "step1_desc": "Kopiera YouTube-videolänken",
    "step2_title": "Klistra in Länk",
    "step2_desc": "Klistra in i rutan ovan",
    "step3_title": "Välj Format",
    "step3_desc": "Välj kvalitet/format",
    "step4_title": "Ladda ner",
    "step4_desc": "Få din fil omedelbart",
    "faq_title": "Vanliga Frågor",
    "faq1_q": "Är det gratis att ladda ner YouTube-videor?",
    "faq1_a": "Ja, vår tjänst är helt gratis. Du kan ladda ner videor i olika format och kvaliteter utan några kostnader.",
    "faq2_q": "Vilka videoformat stöds?",
    "faq2_a": "Vi stöder olika format, inklusive MP4, WebM för video och MP3 för ljud. Du kan välja mellan olika kvalitetsalternativ från 360p till 4K (när det är tillgängligt).",
    "faq3_q": "Är det lagligt att ladda ner YouTube-videor?",
    "faq3_a": "Att ladda ner videor för personligt bruk är generellt acceptabelt. Vänligen respektera dock upphovsrättslagar och innehållsskapares rättigheter. Sprid inte eller använd nedladdat innehåll för kommersiella ändamål utan korrekt tillstånd.",
    "faq4_q": "Hur laddar jag ner en YouTube-video?",
    "faq4_a": "1. Kopiera YouTube-videons URL<br>2. Klistra in den i inmatningsfältet ovan<br>3. Vänta tills de tillgängliga formaten laddas<br>4. Välj ditt föredragna format och kvalitet<br>5. Klicka på nedladdningsknappen",
    "faq5_q": "Finns det några nedladdningsgränser?",
    "faq5_a": "Det finns inga strikta nedladdningsgränser. Vi rekommenderar dock rimlig användning för att säkerställa att tjänsten förblir tillgänglig för alla. Mycket stora filer kan ta längre tid att bearbeta.",
    "copyright": "© 2025 YTGrab. Alla rättigheter förbehållna.",
    "privacy_policy": "Integritetspolicy",
    "terms": "Villkor",
    "contact": "Kontakt",
    "url_error": "Ange en giltig YouTube-URL"
  },
  "th": {
    "title": "ดาวน์โหลดวิดีโอ YouTube ได้อย่างง่ายดาย",
    "description": "ดาวน์โหลดวิดีโอ YouTube ในรูปแบบ MP4 และ MP3 ได้อย่างง่ายดาย โดยไม่มีโฆษณาและฟรี",
    "brand": "YTGrab",
    "faq": "คำถามที่พบบ่อย",
    "language": "ไทย",
    "subtitle": "ดาวน์โหลดวิดีโอและเสียงในหลายรูปแบบอย่างรวดเร็วและง่ายดาย",
    "placeholder": "วางลิงก์ YouTube ที่นี่...",
    "download_button": "ดาวน์โหลด",
    "choose_format": "เลือกรูปแบบ",
    "back": "กลับ",
    "support": "เรารองรับการดาวน์โหลดวิดีโอจาก YouTube ในทุกรูปแบบและคุณภาพที่พร้อมใช้งาน",
    "format": "รูปแบบ",
    "size": "ขนาด",
    "download": "ดาวน์โหลด",
    "instant_download": "ดาวน์โหลดทันที",
    "instant_download_desc": "รับวิดีโอของคุณในไม่กี่วินาทีด้วยเซิร์ฟเวอร์ความเร็วสูงของเรา",
    "multiple_formats": "หลายรูปแบบ",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K และรูปแบบอื่น ๆ อีกมากมายที่พร้อมใช้งาน",
    "easy_to_use": "ใช้งานง่าย",
    "easy_to_use_desc": "วางลิงก์และดาวน์โหลด - ไม่ต้องลงทะเบียน",
    "how_it_works": "วิธีการทำงาน",
    "step1_title": "คัดลอก URL",
    "step1_desc": "คัดลอกลิงก์วิดีโอ YouTube",
    "step2_title": "วางลิงก์",
    "step2_desc": "วางในกล่องด้านบน",
    "step3_title": "เลือกรูปแบบ",
    "step3_desc": "เลือกคุณภาพ/รูปแบบ",
    "step4_title": "ดาวน์โหลด",
    "step4_desc": "รับไฟล์ของคุณทันที",
    "faq_title": "คำถามที่พบบ่อย",
    "faq1_q": "การดาวน์โหลดวิดีโอ YouTube ฟรีหรือไม่?",
    "faq1_a": "ใช่ บริการของเราฟรีทั้งหมด คุณสามารถดาวน์โหลดวิดีโอในรูปแบบและคุณภาพต่าง ๆ ได้โดยไม่มีค่าใช้จ่าย",
    "faq2_q": "รูปแบบวิดีโอใดบ้างที่รองรับ?",
    "faq2_a": "เรารองรับรูปแบบต่าง ๆ รวมถึง MP4, WebM สำหรับวิดีโอ และ MP3 สำหรับเสียง คุณสามารถเลือกจากตัวเลือกคุณภาพต่าง ๆ ตั้งแต่ 360p ถึง 4K (เมื่อมีให้ใช้งาน)",
    "faq3_q": "การดาวน์โหลดวิดีโอ YouTube ถูกกฎหมายหรือไม่?",
    "faq3_a": "การดาวน์โหลดวิดีโอเพื่อใช้งานส่วนตัวโดยทั่วไปเป็นที่ยอมรับได้ อย่างไรก็ตาม โปรดเคารพกฎหมายลิขสิทธิ์และสิทธิ์ของผู้สร้างเนื้อหา อย่าแจกจ่ายหรือใช้เนื้อหาที่ดาวน์โหลดเพื่อวัตถุประสงค์ทางการค้าโดยไม่ได้รับอนุญาตที่เหมาะสม",
    "faq4_q": "ฉันจะดาวน์โหลดวิดีโอ YouTube ได้อย่างไร?",
    "faq4_a": "1. คัดลอก URL วิดีโอ YouTube<br>2. วางลงในช่องป้อนข้อมูลด้านบน<br>3. รอจนกว่ารูปแบบที่พร้อมใช้งานจะโหลด<br>4. เลือกรูปแบบและคุณภาพที่ต้องการ<br>5. คลิกปุ่มดาวน์โหลด",
    "faq5_q": "มีการจำกัดการดาวน์โหลดหรือไม่?",
    "faq5_a": "ไม่มีข้อจำกัดที่เข้มงวดสำหรับการดาวน์โหลด อย่างไรก็ตาม เราแนะนำให้ใช้งานอย่างสมเหตุสมผลเพื่อให้แน่ใจว่าบริการยังคงพร้อมใช้งานสำหรับทุกคน ไฟล์ขนาดใหญ่มากอาจใช้เวลาในการประมวลผลนานขึ้น",
    "copyright": "© 2025 YTGrab. สงวนลิขสิทธิ์ทั้งหมด.",
    "privacy_policy": "นโยบายความเป็นส่วนตัว",
    "terms": "เงื่อนไข",
    "contact": "ติดต่อ",
    "url_error": "โปรดป้อน URL YouTube ที่ถูกต้อง"
  },
  "tr": {
    "title": "YouTube Videolarını Kolayca İndir",
    "description": "YouTube videolarını MP4 ve MP3 formatlarında kolayca, reklamsız ve ücretsiz indirin.",
    "brand": "YTGrab",
    "faq": "Sıkça Sorulan Sorular",
    "language": "Türkçe",
    "subtitle": "Videoları ve sesleri birden fazla formatta hızlı ve kolay bir şekilde indir",
    "placeholder": "YouTube bağlantısını buraya yapıştır...",
    "download_button": "İndir",
    "choose_format": "Format Seç",
    "back": "Geri",
    "support": "YouTube’dan tüm mevcut formatlarda ve kalitelerde video indirmeyi destekliyoruz.",
    "format": "Format",
    "size": "Boyut",
    "download": "İndir",
    "instant_download": "Anında İndirme",
    "instant_download_desc": "Yüksek hızlı sunucularımızla videolarınızı saniyeler içinde alın",
    "multiple_formats": "Çoklu Formatlar",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K ve daha birçok format mevcut",
    "easy_to_use": "Kullanımı Kolay",
    "easy_to_use_desc": "Bağlantıyı yapıştır ve indir - kayıt gerekmez",
    "how_it_works": "Nasıl Çalışır",
    "step1_title": "URL’yi Kopyala",
    "step1_desc": "YouTube video bağlantısını kopyala",
    "step2_title": "Bağlantıyı Yapıştır",
    "step2_desc": "Yukarıdaki kutuya yapıştır",
    "step3_title": "Format Seç",
    "step3_desc": "Kalite/format seç",
    "step4_title": "İndir",
    "step4_desc": "Dosyanızı anında alın",
    "faq_title": "Sıkça Sorulan Sorular",
    "faq1_q": "YouTube videolarını indirmek ücretsiz mi?",
    "faq1_a": "Evet, hizmetimiz tamamen ücretsizdir. Çeşitli formatlarda ve kalitelerde videoları hiçbir maliyet olmadan indirebilirsiniz.",
    "faq2_q": "Hangi video formatları destekleniyor?",
    "faq2_a": "Video için MP4, WebM ve ses için MP3 dahil olmak üzere çeşitli formatları destekliyoruz. 360p’den 4K’ya kadar farklı kalite seçeneklerinden seçim yapabilirsiniz (mevcut olduğunda).",
    "faq3_q": "YouTube videolarını indirmek yasal mı?",
    "faq3_a": "Kişisel kullanım için video indirmek genellikle kabul edilebilir. Ancak, lütfen telif hakkı yasalarına ve içerik oluşturucuların haklarına saygı gösterin. İndirilen içeriği uygun izin olmadan ticari amaçlarla dağıtmayın veya kullanmayın.",
    "faq4_q": "YouTube videosu nasıl indirilir?",
    "faq4_a": "1. YouTube video URL’sini kopyalayın<br>2. Yukarıdaki giriş kutusuna yapıştırın<br>3. Mevcut formatların yüklenmesini bekleyin<br>4. Tercih ettiğiniz formatı ve kaliteyi seçin<br>5. İndir düğmesine tıklayın",
    "faq5_q": "İndirme sınırları var mı?",
    "faq5_a": "İndirmelerde katı bir sınır yok. Ancak, hizmetin herkes için erişilebilir kalmasını sağlamak için makul kullanım öneriyoruz. Çok büyük dosyalar işlenmesi daha uzun sürebilir.",
    "copyright": "© 2025 YTGrab. Tüm hakları saklıdır.",
    "privacy_policy": "Gizlilik Politikası",
    "terms": "Şartlar",
    "contact": "İletişim",
    "url_error": "Lütfen geçerli bir YouTube URL’si girin"
  },
  "vi": {
    "title": "Tải Video YouTube Dễ Dàng",
    "description": "Tải video YouTube ở định dạng MP4 và MP3 dễ dàng, không có quảng cáo và miễn phí.",
    "brand": "YTGrab",
    "faq": "Câu Hỏi Thường Gặp",
    "language": "Tiếng Việt",
    "subtitle": "Tải video và âm thanh ở nhiều định dạng nhanh chóng và dễ dàng",
    "placeholder": "Dán liên kết YouTube tại đây...",
    "download_button": "Tải xuống",
    "choose_format": "Chọn Định dạng",
    "back": "Quay lại",
    "support": "Chúng tôi hỗ trợ tải video từ YouTube ở tất cả các định dạng và chất lượng có sẵn.",
    "format": "Định dạng",
    "size": "Kích thước",
    "download": "Tải xuống",
    "instant_download": "Tải Xuống Ngay Lập Tức",
    "instant_download_desc": "Nhận video của bạn trong vài giây với các máy chủ tốc độ cao của chúng tôi",
    "multiple_formats": "Nhiều Định dạng",
    "multiple_formats_desc": "MP4, MP3, 1080p, 4K và nhiều định dạng khác có sẵn",
    "easy_to_use": "Dễ Sử Dụng",
    "easy_to_use_desc": "Dán liên kết và tải xuống - không cần đăng ký",
    "how_it_works": "Cách Hoạt Động",
    "step1_title": "Sao chép URL",
    "step1_desc": "Sao chép liên kết video YouTube",
    "step2_title": "Dán Liên kết",
    "step2_desc": "Dán vào ô phía trên",
    "step3_title": "Chọn Định dạng",
    "step3_desc": "Chọn chất lượng/định dạng",
    "step4_title": "Tải xuống",
    "step4_desc": "Nhận tệp của bạn ngay lập tức",
    "faq_title": "Câu Hỏi Thường Gặp",
    "faq1_q": "Tải video YouTube có miễn phí không?",
    "faq1_a": "Có, dịch vụ của chúng tôi hoàn toàn miễn phí. Bạn có thể tải video ở nhiều định dạng và chất lượng mà không tốn bất kỳ chi phí nào.",
    "faq2_q": "Những định dạng video nào được hỗ trợ?",
    "faq2_a": "Chúng tôi hỗ trợ nhiều định dạng, bao gồm MP4, WebM cho video và MP3 cho âm thanh. Bạn có thể chọn từ các tùy chọn chất lượng khác nhau, từ 360p đến 4K (khi có sẵn).",
    "faq3_q": "Tải video YouTube có hợp pháp không?",
    "faq3_a": "Tải video để sử dụng cá nhân thường được chấp nhận. Tuy nhiên, vui lòng tôn trọng luật bản quyền và quyền của những người tạo nội dung. Không phân phối hoặc sử dụng nội dung đã tải xuống cho mục đích thương mại nếu không có sự cho phép thích hợp.",
    "faq4_q": "Làm thế nào để tải video YouTube?",
    "faq4_a": "1. Sao chép URL video YouTube<br>2. Dán nó vào ô nhập liệu phía trên<br>3. Chờ các định dạng có sẵn được tải<br>4. Chọn định dạng và chất lượng ưa thích của bạn<br>5. Nhấn nút tải xuống",
    "faq5_q": "Có giới hạn tải xuống nào không?",
    "faq5_a": "Không có giới hạn nghiêm ngặt về tải xuống. Tuy nhiên, chúng tôi khuyên bạn nên sử dụng hợp lý để đảm bảo dịch vụ vẫn sẵn có cho mọi người. Các tệp rất lớn có thể mất nhiều thời gian hơn để xử lý.",
    "copyright": "© 2025 YTGrab. Bảo lưu mọi quyền.",
    "privacy_policy": "Chính sách Bảo mật",
    "terms": "Điều khoản",
    "contact": "Liên hệ",
    "url_error": "Vui lòng nhập URL YouTube hợp lệ"
  },
  "zh": {
    "title": "轻松下载YouTube视频",
    "description": "以MP4和MP3格式轻松下载YouTube视频，无广告且免费。",
    "brand": "YTGrab",
    "faq": "常见问题",
    "language": "中文",
    "subtitle": "在多种格式中快速轻松地下载视频和音频",
    "placeholder": "在此粘贴YouTube链接...",
    "download_button": "下载",
    "choose_format": "选择格式",
    "back": "返回",
    "support": "我们支持以所有可用格式和质量从YouTube下载视频。",
    "format": "格式",
    "size": "大小",
    "download": "下载",
    "instant_download": "即时下载",
    "instant_download_desc": "通过我们的高速服务器在几秒钟内获取您的视频",
    "multiple_formats": "多种格式",
    "multiple_formats_desc": "MP4、MP3、1080p、4K等多种格式可用",
    "easy_to_use": "易于使用",
    "easy_to_use_desc": "粘贴链接并下载 - 无需注册",
    "how_it_works": "工作原理",
    "step1_title": "复制URL",
    "step1_desc": "复制YouTube视频链接",
    "step2_title": "粘贴链接",
    "step2_desc": "粘贴到上面的框中",
    "step3_title": "选择格式",
    "step3_desc": "选择质量/格式",
    "step4_title": "下载",
    "step4_desc": "立即获取您的文件",
    "faq_title": "常见问题",
    "faq1_q": "下载YouTube视频是免费的吗？",
    "faq1_a": "是的，我们的服务完全免费。您可以免费下载各种格式和质量的视频。",
    "faq2_q": "支持哪些视频格式？",
    "faq2_a": "我们支持多种格式，包括用于视频的MP4、WebM和用于音频的MP3。您可以从360p到4K的不同质量选项中选择（如果可用）。",
    "faq3_q": "下载YouTube视频合法吗？",
    "faq3_a": "为个人使用下载视频通常是可以接受的。但是，请尊重版权法和内容创作者的权利。未经适当授权，请勿分发或将下载的内容用于商业目的。",
    "faq4_q": "如何下载YouTube视频？",
    "faq4_a": "1. 复制YouTube视频的URL<br>2. 将其粘贴到上面的输入框中<br>3. 等待可用格式加载<br>4. 选择您喜欢的格式和质量<br>5. 点击下载按钮",
    "faq5_q": "有下载限制吗？",
    "faq5_a": "下载没有严格的限制。但是，我们建议合理使用以确保服务对所有人保持可用。非常大的文件可能需要更长的处理时间。",
    "copyright": "© 2025 YTGrab。保留所有权利。",
    "privacy_policy": "隐私政策",
    "terms": "条款",
    "contact": "联系我们",
    "url_error": "请输入有效的YouTube URL"
  }
}

# Default language
def get_lang():
    return session.get('lang', 'en')

@app.route('/', methods=['GET', 'POST'])
def index():
    url = request.form.get('url') if request.method == 'POST' else request.args.get('url')
    formats = []
    thumbnail = None
    title = None
    error = None

    if url:
        ydl_opts = {
            'quiet': True,
            'no_warnings': True,
            'extract_flat': 'in_playlist',
            'timeout': 10,
            'nocheckcertificate': True,
            'http_headers': {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
            },
        }
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=False)
                thumbnail = info.get('thumbnail')
                title = info.get('title')
                
                # Standard format definitions
                format_definitions = [
                    {'id': '360', 'name': '360p MP4', 'max_height': 360, 'vcodec': 'avc1'},
                    {'id': '480', 'name': '480p MP4', 'max_height': 480, 'vcodec': 'avc1'},
                    {'id': '720', 'name': '720p MP4', 'max_height': 720, 'vcodec': 'avc1'},
                    {'id': 'best', 'name': 'Best Quality', 'max_height': None, 'vcodec': None},
                    {'id': '140', 'name': 'MP3 Audio', 'audio_only': True}
                ]
                
                available_formats = info.get('formats', [])
                
                for fmt_def in format_definitions:
                    if fmt_def.get('audio_only'):
                        # Handle audio format
                        audio_format = next(
                            (f for f in available_formats if f.get('format_id') == '140'), 
                            None
                        )
                        if audio_format:
                            formats.append({
                                'format_id': '140',
                                'display_name': 'MP3 Audio',
                                'download_format': 'mp3',
                                'filesize': audio_format.get('filesize') or audio_format.get('filesize_approx'),
                                'height': 'Audio'
                            })
                    else:
                        # Handle video formats
                        matching_formats = []
                        for f in available_formats:
                            # Skip formats without height or video codec
                            if f.get('height') is None or f.get('vcodec') is None:
                                continue
                            
                            # Check if format matches our criteria
                            height_ok = (fmt_def['max_height'] is None) or (f.get('height', 0) <= fmt_def['max_height'])
                            vcodec_ok = (fmt_def['vcodec'] is None) or (f.get('vcodec', '').startswith(fmt_def['vcodec']))
                            ext_ok = f.get('ext') == 'mp4'
                            has_audio = f.get('acodec') != 'none'
                            
                            if height_ok and vcodec_ok and ext_ok and has_audio:
                                matching_formats.append(f)
                        
                        if matching_formats:
                            # Get the best quality match
                            best_format = max(matching_formats, key=lambda x: x.get('tbr', 0))
                            formats.append({
                                'format_id': fmt_def['id'],
                                'display_name': fmt_def['name'],
                                'download_format': 'mp4',
                                'filesize': best_format.get('filesize') or best_format.get('filesize_approx'),
                                'height': best_format.get('height')
                            })
                
        except Exception as e:
            error = str(e)
            logger.error(f"Error processing URL: {error}")

    return render_template('index.html',
                         formats=formats,
                         url=url,
                         thumbnail=thumbnail,
                         title=title,
                         error=error,
                         lang=get_lang(),
                         translations=translations)


@app.route('/set_language/<language>')
def set_language(language):
    if language in translations:
        session['lang'] = language
    return redirect(url_for('index'))

@app.route('/download/<format_id>')
def download(format_id):
    url = request.args.get('url')
    if not url:
        return "No URL provided", 400
    import tempfile
    import platform
    import io
    import random
    import shutil
    
    
    temp_dir = tempfile.mkdtemp()
    logger.info(f"Created temp directory: {temp_dir}")

    try:
        user_agent = random.choice([
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
        ])
        logger.info(f"Using user agent: {user_agent}")

        is_audio = format_id == '140'
        
        # Format definitions must match the index route
        format_definitions = {
            '360': {'max_height': 360, 'vcodec': 'avc1'},
            '480': {'max_height': 480, 'vcodec': 'avc1'},
            '720': {'max_height': 720, 'vcodec': 'avc1'},
            'best': {'max_height': None, 'vcodec': None},
            '140': {'audio_only': True}
        }
        
        fmt_def = format_definitions.get(format_id, format_definitions['720'])
        
        ydl_opts = {
            'outtmpl': os.path.join(temp_dir, '%(title)s.%(ext)s'),
            'quiet': False,
            'no_warnings': False,
            'retries': 10,
            'fragment_retries': 10,
            'extractor_retries': 3,
            'socket_timeout': 30,
            'nocheckcertificate': True,
            'http_headers': {'User-Agent': user_agent},
        }

        if is_audio:
            ydl_opts.update({
                'format': 'bestaudio/best',
                'postprocessors': [{
                    'key': 'FFmpegExtractAudio',
                    'preferredcodec': 'mp3',
                    'preferredquality': '192',
                }],
            })
        else:
            # Build format query safely
            format_query = []
            if fmt_def['max_height'] is not None:
                format_query.append(f"height<={fmt_def['max_height']}")
            if fmt_def['vcodec'] is not None:
                format_query.append(f"vcodec^={fmt_def['vcodec']}")
            
            format_query.append('ext=mp4')
            
            ydl_opts.update({
                'format': '+'.join(format_query) + '+bestaudio[ext=m4a]/best',
                'merge_output_format': 'mp4',
                'postprocessors': [{
                    'key': 'FFmpegVideoConvertor',
                    'preferedformat': 'mp4',
                }],
            })

        # Rest of the download function remains the same...
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            filename = ydl.prepare_filename(info)
            
            if is_audio:
                file_path = os.path.splitext(filename)[0] + '.mp3'
            else:
                file_path = os.path.splitext(filename)[0] + '.mp4'
                if not os.path.exists(file_path):
                    file_path = filename  # Fallback

            if not os.path.exists(file_path):
                raise FileNotFoundError(f"Downloaded file not found: {file_path}")
            
            file_size = os.path.getsize(file_path)
            logger.info(f"Downloaded {file_path} ({file_size} bytes)")

            if platform.system() == 'Windows':
                with open(file_path, 'rb') as f:
                    file_data = io.BytesIO(f.read())
                response = send_file(
                    file_data,
                    as_attachment=True,
                    download_name=os.path.basename(file_path),
                    mimetype='audio/mp3' if is_audio else 'video/mp4'
                )
            else:
                response = send_file(
                    file_path,
                    as_attachment=True,
                    download_name=os.path.basename(file_path),
                    mimetype='audio/mp3' if is_audio else 'video/mp4'
                )
            
            @response.call_on_close
            def cleanup():
                try:
                    shutil.rmtree(temp_dir)
                except Exception as e:
                    logger.warning(f"Cleanup failed: {e}")
            
            return response
            
    except Exception as e:
        logger.error(f"Download failed: {e}")
        try:
            shutil.rmtree(temp_dir)
        except:
            pass
        return f"Download failed: {str(e)}", 500

    
if __name__ == '__main__':
    if not os.path.exists('downloads'):
        os.makedirs('downloads')
    app.run(host='0.0.0.0', port=5000, debug=True)