[phases.setup]
nixPkgs = [
  "ffmpeg", 
  "python313", 
  "python313Packages.pip", 
  "python313Packages.virtualenv",
  "glibcLocales"  # Add locale support
]

[phases.install]
cmds = [
  # Set locale
  "export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive",
  "export LANG=en_US.UTF-8",
  "export LC_ALL=en_US.UTF-8",
  
  # Create and activate virtual environment
  "python -m venv venv",
  ". venv/bin/activate",
  ". venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". venv/bin/activate",
  # Skip compilation to avoid potential issues
  "echo 'Build phase completed'"
]

[start]
cmd = ". venv/bin/activate && python app.py"

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
FLASK_APP = "app.py"
FLASK_ENV = "production"
# Set locale environment variables
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"

# Use nixos-23.11 channel which should have better support
[nixpkgs]
channel = "nixos-23.11"