[phases.setup]
nixPkgs = ["ffmpeg", "python313", "python313Packages.pip", "python313Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". venv/bin/activate",
  "python -c 'import compileall; compileall.compile_dir(\".\", quiet=1)'"
]

[start]
cmd = ". venv/bin/activate && python app.py"

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
FLASK_APP = "app.py"
FLASK_ENV = "production"

# Specify a more recent nixpkgs channel to ensure Python 3.13 support
[nixpkgs]
channel = "unstable"